using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class CharacterPropertyDisplay : ConfigData<CharacterPropertyDisplayItem, short>
{
	public static CharacterPropertyDisplay Instance = new CharacterPropertyDisplay();

	private readonly HashSet<string> RequiredFields = new HashSet<string>
	{
		"TemplateId", "Type", "Name", "ShortName", "Desc", "Icon", "TipsBigIcon", "TipsIcon", "PositiveColor", "NegativeColor",
		"DisplayFix"
	};

	internal override int ToInt(short value)
	{
		return value;
	}

	internal override short ToTemplateId(int value)
	{
		return (short)value;
	}

	private void CreateItems0()
	{
		_dataArray.Add(new CharacterPropertyDisplayItem(0, ECharacterPropertyDisplayType.Strength, 0, 0, 1, "sp_icon_attribute_0", "mousetip_zhuyao_big_0", "mousetip_zhuyao_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(1, ECharacterPropertyDisplayType.Dexterity, 2, 2, 3, "sp_icon_attribute_1", "mousetip_zhuyao_big_1", "mousetip_zhuyao_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(2, ECharacterPropertyDisplayType.Concentration, 4, 4, 5, "sp_icon_attribute_2", "mousetip_zhuyao_big_2", "mousetip_zhuyao_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(3, ECharacterPropertyDisplayType.Vitality, 6, 6, 7, "sp_icon_attribute_3", "mousetip_zhuyao_big_3", "mousetip_zhuyao_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(4, ECharacterPropertyDisplayType.Energy, 8, 8, 9, "sp_icon_attribute_4", "mousetip_zhuyao_big_4", "mousetip_zhuyao_4", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(5, ECharacterPropertyDisplayType.Intelligence, 10, 10, 11, "sp_icon_attribute_5", "mousetip_zhuyao_big_5", "mousetip_zhuyao_5", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(6, ECharacterPropertyDisplayType.HitRateStrength, 12, 12, 13, "sp_icon_attribute_10", "mousetip_mingzhong_big_0", "mousetip_mingzhong_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(7, ECharacterPropertyDisplayType.HitRateTechnique, 14, 14, 15, "sp_icon_attribute_12", "mousetip_mingzhong_big_1", "mousetip_mingzhong_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(8, ECharacterPropertyDisplayType.HitRateSpeed, 16, 16, 17, "sp_icon_attribute_14", "mousetip_mingzhong_big_2", "mousetip_mingzhong_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(9, ECharacterPropertyDisplayType.HitRateMind, 18, 18, 19, "sp_icon_attribute_16", "mousetip_mingzhong_big_3", "mousetip_mingzhong_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(10, ECharacterPropertyDisplayType.PenetrateOfOuter, 20, 20, 21, "sp_icon_attribute_6", "mousetip_gongji_big_0", "mousetip_gongji_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(11, ECharacterPropertyDisplayType.PenetrateOfInner, 22, 22, 23, "sp_icon_attribute_7", "mousetip_gongji_big_1", "mousetip_gongji_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(12, ECharacterPropertyDisplayType.AvoidRateStrength, 24, 24, 25, "sp_icon_attribute_11", "mousetip_huajie_big_0", "mousetip_huajie_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(13, ECharacterPropertyDisplayType.AvoidRateTechnique, 26, 26, 27, "sp_icon_attribute_13", "mousetip_huajie_big_1", "mousetip_huajie_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(14, ECharacterPropertyDisplayType.AvoidRateSpeed, 28, 28, 29, "sp_icon_attribute_15", "mousetip_huajie_big_2", "mousetip_huajie_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(15, ECharacterPropertyDisplayType.AvoidRateMind, 30, 30, 31, "sp_icon_attribute_17", "mousetip_huajie_big_3", "mousetip_huajie_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(16, ECharacterPropertyDisplayType.PenetrateResistOfOuter, 32, 32, 33, "sp_icon_attribute_8", "mousetip_fangyu_big_0", "mousetip_fangyu_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(17, ECharacterPropertyDisplayType.PenetrateResistOfInner, 34, 34, 35, "sp_icon_attribute_9", "mousetip_fangyu_big_1", "mousetip_fangyu_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(18, ECharacterPropertyDisplayType.RecoveryOfStance, 36, 36, 37, "sp_icon_attribute_18", "mousetip_ciyao_big_0", "mousetip_ciyao_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(19, ECharacterPropertyDisplayType.RecoveryOfBreath, 38, 38, 39, "sp_icon_attribute_18", "mousetip_ciyao_big_0", "mousetip_ciyao_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(20, ECharacterPropertyDisplayType.MoveSpeed, 40, 40, 41, "sp_icon_attribute_19", "mousetip_ciyao_big_1", "mousetip_ciyao_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(21, ECharacterPropertyDisplayType.RecoveryOfFlaw, 42, 42, 43, "sp_icon_attribute_19", "mousetip_ciyao_big_1", "mousetip_ciyao_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(22, ECharacterPropertyDisplayType.CastSpeed, 44, 44, 45, "sp_icon_attribute_20", "mousetip_ciyao_big_2", "mousetip_ciyao_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(23, ECharacterPropertyDisplayType.RecoveryOfBlockedAcupoint, 46, 46, 47, "sp_icon_attribute_20", "mousetip_ciyao_big_2", "mousetip_ciyao_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(24, ECharacterPropertyDisplayType.WeaponSwitchSpeed, 48, 48, 49, "sp_icon_attribute_21", "mousetip_ciyao_big_3", "mousetip_ciyao_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(25, ECharacterPropertyDisplayType.AttackSpeed, 50, 50, 51, "sp_icon_attribute_21", "mousetip_ciyao_big_3", "mousetip_ciyao_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(26, ECharacterPropertyDisplayType.InnerRatio, 52, 52, 53, "sp_icon_attribute_22", "mousetip_ciyao_big_4", "mousetip_ciyao_4", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(27, ECharacterPropertyDisplayType.RecoveryOfQiDisorder, 54, 54, 55, "sp_icon_attribute_22", "mousetip_ciyao_big_4", "mousetip_ciyao_4", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(28, ECharacterPropertyDisplayType.ResistOfHotPoison, 56, 56, 57, "sp_icon_poison_0", "mousetip_duxing_big_0", "mousetip_duxing_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(29, ECharacterPropertyDisplayType.ResistOfGloomyPoison, 58, 58, 59, "sp_icon_poison_1", "mousetip_duxing_big_1", "mousetip_duxing_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(30, ECharacterPropertyDisplayType.ResistOfColdPoison, 60, 60, 61, "sp_icon_poison_2", "mousetip_duxing_big_2", "mousetip_duxing_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(31, ECharacterPropertyDisplayType.ResistOfRedPoison, 62, 62, 63, "sp_icon_poison_3", "mousetip_duxing_big_3", "mousetip_duxing_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(32, ECharacterPropertyDisplayType.ResistOfRottenPoison, 64, 64, 65, "sp_icon_poison_4", "mousetip_duxing_big_4", "mousetip_duxing_4", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(33, ECharacterPropertyDisplayType.ResistOfIllusoryPoison, 66, 66, 67, "sp_icon_poison_5", "mousetip_duxing_big_5", "mousetip_duxing_5", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(34, ECharacterPropertyDisplayType.QualificationMusic, 68, 68, 69, null, "mousetip_jiyi_big_0", "mousetip_jiyi_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(35, ECharacterPropertyDisplayType.QualificationChess, 70, 70, 71, null, "mousetip_jiyi_big_1", "mousetip_jiyi_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(36, ECharacterPropertyDisplayType.QualificationPoem, 72, 72, 73, null, "mousetip_jiyi_big_2", "mousetip_jiyi_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(37, ECharacterPropertyDisplayType.QualificationPainting, 74, 74, 75, null, "mousetip_jiyi_big_3", "mousetip_jiyi_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(38, ECharacterPropertyDisplayType.QualificationMath, 76, 76, 77, null, "mousetip_jiyi_big_4", "mousetip_jiyi_4", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(39, ECharacterPropertyDisplayType.QualificationAppraisal, 78, 78, 79, null, "mousetip_jiyi_big_5", "mousetip_jiyi_5", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(40, ECharacterPropertyDisplayType.QualificationForging, 80, 80, 81, null, "mousetip_jiyi_big_6", "mousetip_jiyi_6", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(41, ECharacterPropertyDisplayType.QualificationWoodworking, 82, 82, 83, null, "mousetip_jiyi_big_7", "mousetip_jiyi_7", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(42, ECharacterPropertyDisplayType.QualificationMedicine, 84, 84, 85, null, "mousetip_jiyi_big_8", "mousetip_jiyi_8", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(43, ECharacterPropertyDisplayType.QualificationToxicology, 86, 86, 87, null, "mousetip_jiyi_big_9", "mousetip_jiyi_9", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(44, ECharacterPropertyDisplayType.QualificationWeaving, 88, 88, 89, null, "mousetip_jiyi_big_10", "mousetip_jiyi_10", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(45, ECharacterPropertyDisplayType.QualificationJade, 90, 90, 91, null, "mousetip_jiyi_big_11", "mousetip_jiyi_11", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(46, ECharacterPropertyDisplayType.QualificationTaoism, 92, 92, 93, null, "mousetip_jiyi_big_12", "mousetip_jiyi_12", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(47, ECharacterPropertyDisplayType.QualificationBuddhism, 94, 94, 95, null, "mousetip_jiyi_big_13", "mousetip_jiyi_13", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(48, ECharacterPropertyDisplayType.QualificationCooking, 96, 96, 97, null, "mousetip_jiyi_big_14", "mousetip_jiyi_14", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(49, ECharacterPropertyDisplayType.QualificationEclectic, 98, 98, 99, null, "mousetip_jiyi_big_15", "mousetip_jiyi_15", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(50, ECharacterPropertyDisplayType.AttainmentMusic, 100, 101, 102, "sp_14_iconjiyizhanshi_0", "mousetip_jiyi_big_0", "mousetip_jiyi_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(51, ECharacterPropertyDisplayType.AttainmentChess, 103, 104, 105, "sp_14_iconjiyizhanshi_1", "mousetip_jiyi_big_1", "mousetip_jiyi_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(52, ECharacterPropertyDisplayType.AttainmentPoem, 106, 107, 108, "sp_14_iconjiyizhanshi_2", "mousetip_jiyi_big_2", "mousetip_jiyi_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(53, ECharacterPropertyDisplayType.AttainmentPainting, 109, 110, 111, "sp_14_iconjiyizhanshi_3", "mousetip_jiyi_big_3", "mousetip_jiyi_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(54, ECharacterPropertyDisplayType.AttainmentMath, 112, 113, 114, "sp_14_iconjiyizhanshi_4", "mousetip_jiyi_big_4", "mousetip_jiyi_4", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(55, ECharacterPropertyDisplayType.AttainmentAppraisal, 115, 116, 117, "sp_14_iconjiyizhanshi_5", "mousetip_jiyi_big_5", "mousetip_jiyi_5", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(56, ECharacterPropertyDisplayType.AttainmentForging, 118, 119, 120, "sp_14_iconjiyizhanshi_6", "mousetip_jiyi_big_6", "mousetip_jiyi_6", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(57, ECharacterPropertyDisplayType.AttainmentWoodworking, 121, 122, 123, "sp_14_iconjiyizhanshi_7", "mousetip_jiyi_big_7", "mousetip_jiyi_7", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(58, ECharacterPropertyDisplayType.AttainmentMedicine, 124, 125, 126, "sp_14_iconjiyizhanshi_10", "mousetip_jiyi_big_8", "mousetip_jiyi_8", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(59, ECharacterPropertyDisplayType.AttainmentToxicology, 127, 128, 129, "sp_14_iconjiyizhanshi_11", "mousetip_jiyi_big_9", "mousetip_jiyi_9", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
	}

	private void CreateItems1()
	{
		_dataArray.Add(new CharacterPropertyDisplayItem(60, ECharacterPropertyDisplayType.AttainmentWeaving, 130, 131, 132, "sp_14_iconjiyizhanshi_9", "mousetip_jiyi_big_10", "mousetip_jiyi_10", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(61, ECharacterPropertyDisplayType.AttainmentJade, 133, 134, 135, "sp_14_iconjiyizhanshi_8", "mousetip_jiyi_big_11", "mousetip_jiyi_11", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(62, ECharacterPropertyDisplayType.AttainmentTaoism, 136, 137, 138, "sp_14_iconjiyizhanshi_12", "mousetip_jiyi_big_12", "mousetip_jiyi_12", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(63, ECharacterPropertyDisplayType.AttainmentBuddhism, 139, 140, 141, "sp_14_iconjiyizhanshi_13", "mousetip_jiyi_big_13", "mousetip_jiyi_13", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(64, ECharacterPropertyDisplayType.AttainmentCooking, 142, 143, 144, "sp_14_iconjiyizhanshi_14", "mousetip_jiyi_big_14", "mousetip_jiyi_14", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(65, ECharacterPropertyDisplayType.AttainmentEclectic, 145, 146, 147, "sp_14_iconjiyizhanshi_15", "mousetip_jiyi_big_15", "mousetip_jiyi_15", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(66, ECharacterPropertyDisplayType.QualificationNeigong, 148, 148, 149, null, "mousetip_gongfa_big_0", "mousetip_gongfa_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(67, ECharacterPropertyDisplayType.QualificationPosing, 150, 150, 151, null, "mousetip_gongfa_big_1", "mousetip_gongfa_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(68, ECharacterPropertyDisplayType.QualificationStunt, 152, 152, 153, null, "mousetip_gongfa_big_2", "mousetip_gongfa_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(69, ECharacterPropertyDisplayType.QualificationFistAndPalm, 154, 154, 155, null, "mousetip_gongfa_big_3", "mousetip_gongfa_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(70, ECharacterPropertyDisplayType.QualificationFinger, 156, 156, 157, null, "mousetip_gongfa_big_4", "mousetip_gongfa_4", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(71, ECharacterPropertyDisplayType.QualificationLeg, 158, 158, 159, null, "mousetip_gongfa_big_5", "mousetip_gongfa_5", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(72, ECharacterPropertyDisplayType.QualificationThrow, 160, 160, 161, null, "mousetip_gongfa_big_6", "mousetip_gongfa_6", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(73, ECharacterPropertyDisplayType.QualificationSword, 162, 162, 163, null, "mousetip_gongfa_big_7", "mousetip_gongfa_7", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(74, ECharacterPropertyDisplayType.QualificationBlade, 164, 164, 165, null, "mousetip_gongfa_big_8", "mousetip_gongfa_8", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(75, ECharacterPropertyDisplayType.QualificationPolearm, 166, 166, 167, null, "mousetip_gongfa_big_9", "mousetip_gongfa_9", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(76, ECharacterPropertyDisplayType.QualificationSpecial, 168, 168, 169, null, "mousetip_gongfa_big_10", "mousetip_gongfa_10", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(77, ECharacterPropertyDisplayType.QualificationWhip, 170, 170, 171, null, "mousetip_gongfa_big_11", "mousetip_gongfa_11", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(78, ECharacterPropertyDisplayType.QualificationControllableShot, 172, 172, 173, null, "mousetip_gongfa_big_12", "mousetip_gongfa_12", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(79, ECharacterPropertyDisplayType.QualificationCombatMusic, 174, 174, 175, null, "mousetip_gongfa_big_13", "mousetip_gongfa_13", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(80, ECharacterPropertyDisplayType.AttainmentNeigong, 176, 177, 178, "sp_18_iconwuxuezhanshi_0", "mousetip_gongfa_big_0", "mousetip_gongfa_0", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(81, ECharacterPropertyDisplayType.AttainmentPosing, 179, 180, 181, "sp_18_iconwuxuezhanshi_1", "mousetip_gongfa_big_1", "mousetip_gongfa_1", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(82, ECharacterPropertyDisplayType.AttainmentStunt, 182, 183, 184, "sp_18_iconwuxuezhanshi_2", "mousetip_gongfa_big_2", "mousetip_gongfa_2", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(83, ECharacterPropertyDisplayType.AttainmentFistAndPalm, 185, 186, 187, "sp_18_iconwuxuezhanshi_3", "mousetip_gongfa_big_3", "mousetip_gongfa_3", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(84, ECharacterPropertyDisplayType.AttainmentFinger, 188, 189, 190, "sp_18_iconwuxuezhanshi_4", "mousetip_gongfa_big_4", "mousetip_gongfa_4", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(85, ECharacterPropertyDisplayType.AttainmentLeg, 191, 192, 193, "sp_18_iconwuxuezhanshi_5", "mousetip_gongfa_big_5", "mousetip_gongfa_5", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(86, ECharacterPropertyDisplayType.AttainmentThrow, 194, 195, 196, "sp_18_iconwuxuezhanshi_6", "mousetip_gongfa_big_6", "mousetip_gongfa_6", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(87, ECharacterPropertyDisplayType.AttainmentSword, 197, 198, 199, "sp_18_iconwuxuezhanshi_7", "mousetip_gongfa_big_7", "mousetip_gongfa_7", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(88, ECharacterPropertyDisplayType.AttainmentBlade, 200, 201, 202, "sp_18_iconwuxuezhanshi_8", "mousetip_gongfa_big_8", "mousetip_gongfa_8", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(89, ECharacterPropertyDisplayType.AttainmentPolearm, 203, 204, 205, "sp_18_iconwuxuezhanshi_9", "mousetip_gongfa_big_9", "mousetip_gongfa_9", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(90, ECharacterPropertyDisplayType.AttainmentSpecial, 206, 207, 208, "sp_18_iconwuxuezhanshi_10", "mousetip_gongfa_big_10", "mousetip_gongfa_10", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(91, ECharacterPropertyDisplayType.AttainmentWhip, 209, 210, 211, "sp_18_iconwuxuezhanshi_11", "mousetip_gongfa_big_11", "mousetip_gongfa_11", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(92, ECharacterPropertyDisplayType.AttainmentControllableShot, 212, 213, 214, "sp_18_iconwuxuezhanshi_12", "mousetip_gongfa_big_12", "mousetip_gongfa_12", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(93, ECharacterPropertyDisplayType.AttainmentCombatMusic, 215, 216, 217, "sp_18_iconwuxuezhanshi_13", "mousetip_gongfa_big_13", "mousetip_gongfa_13", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(94, ECharacterPropertyDisplayType.PersonalityCalm, 218, 218, 219, "sp_personality_0", null, "mousetip_qiyuan_0", isPercent: false, "yellow", "yellow", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(95, ECharacterPropertyDisplayType.PersonalityClever, 220, 220, 221, "sp_personality_1", null, "mousetip_qiyuan_1", isPercent: false, "yellow", "yellow", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(96, ECharacterPropertyDisplayType.PersonalityEnthusiastic, 222, 222, 223, "sp_personality_2", null, "mousetip_qiyuan_2", isPercent: false, "yellow", "yellow", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(97, ECharacterPropertyDisplayType.PersonalityBrave, 224, 224, 225, "sp_personality_3", null, "mousetip_qiyuan_3", isPercent: false, "yellow", "yellow", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(98, ECharacterPropertyDisplayType.PersonalityFirm, 226, 226, 227, "sp_personality_4", null, "mousetip_qiyuan_4", isPercent: false, "yellow", "yellow", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(99, ECharacterPropertyDisplayType.PersonalityLucky, 228, 228, 229, "sp_personality_5", null, "mousetip_qiyuan_5", isPercent: false, "yellow", "yellow", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(100, ECharacterPropertyDisplayType.PersonalityPerceptive, 230, 230, 231, "sp_personality_6", null, "mousetip_qiyuan_6", isPercent: false, "yellow", "yellow", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(101, ECharacterPropertyDisplayType.Attraction, 232, 232, 233, null, "mousetip_meili_big", "mousetip_meili", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(102, ECharacterPropertyDisplayType.Fertility, 234, 234, 235, null, "mousetip_shengyu_big", "mousetip_shengyu", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(103, ECharacterPropertyDisplayType.HobbyChangingPeriod, 236, 236, 237, null, "mousetip_xiwu_big", "mousetip_xiwu", isPercent: false, "yellow", "yellow", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(104, ECharacterPropertyDisplayType.Experience, 238, 238, 239, "sp_icon_liliankuang", null, null, isPercent: false, null, null, isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(105, ECharacterPropertyDisplayType.MaxHealth, 240, 240, 241, null, "mousetip_shouming_big", "mousetip_shouming", isPercent: false, null, null, isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(106, ECharacterPropertyDisplayType.MaxNeili, 242, 242, 243, null, "mousetip_neilizongliang_big", "mousetip_neilizongliang", isPercent: false, null, null, isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(107, ECharacterPropertyDisplayType.AttainmentDivinePower, 244, 245, 246, "sp_18_iconwuxuezhanshi_14", "mousetip_gongfa_big_14", "mousetip_gongfa_14", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(108, ECharacterPropertyDisplayType.AttainmentGhostTechnique, 247, 248, 249, "sp_18_iconwuxuezhanshi_15", "mousetip_gongfa_big_15", "mousetip_gongfa_15", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(109, ECharacterPropertyDisplayType.LifeSkillBookReadEfficiency, 250, 250, 251, null, null, "mousetip_readingefficiency", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(110, ECharacterPropertyDisplayType.CombatSkillBookReadEfficiency, 250, 250, 252, null, null, "mousetip_readingefficiency", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(111, ECharacterPropertyDisplayType.CombatSkillProficiency, 253, 253, 254, null, "mousetip_actualcombat_big", "mousetip_actualcombat", isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(112, ECharacterPropertyDisplayType.CricketLuckPoint, 255, 255, 256, null, null, null, isPercent: false, "brightblue", "brightred", isInverse: false, -1, isDisplaySpecially: false));
	}

	public override void Init()
	{
		base.Init();
		_dataArray = new List<CharacterPropertyDisplayItem>(113);
		CreateItems0();
		CreateItems1();
	}
}
