using System.Collections.Generic;
using Config.Common;

namespace Config;

public static class ConfigCollection
{
	public static readonly IConfigData[] Items = new IConfigData[243]
	{
		LocalSurnames.Instance,
		LocalNames.Instance,
		LocalZangNames.Instance,
		LocalTownNames.Instance,
		LocalMonasticTitles.Instance,
		Accessory.Instance,
		Adventure.Instance,
		AdventureItemDropRate.Instance,
		AdventureLifeSkillRequirement.Instance,
		AdventureRemakeMapBlock.Instance,
		AdventureTerrain.Instance,
		AdventureType.Instance,
		AgeEffect.Instance,
		AiAction.Instance,
		AiCondition.Instance,
		AiData.Instance,
		AiGroup.Instance,
		AiNode.Instance,
		AiParam.Instance,
		AiRelations.Instance,
		Animal.Instance,
		Armor.Instance,
		AvatarClothColors.Instance,
		AvatarElements.Instance,
		AvatarExtraParts.Instance,
		AvatarEyeballColors.Instance,
		AvatarFeatureColors.Instance,
		AvatarHairColors.Instance,
		AvatarHead.Instance,
		AvatarLipColors.Instance,
		AvatarSkinColors.Instance,
		BecomeEnemyType.Instance,
		BehaviorType.Instance,
		BigEventKey.Instance,
		BodyPart.Instance,
		Boss.Instance,
		BuildingBlock.Instance,
		BuildingFormula.Instance,
		BuildingScale.Instance,
		Carrier.Instance,
		CatchThiefLevel.Instance,
		CatchThiefPlace.Instance,
		Character.Instance,
		CharacterDeathType.Instance,
		CharacterFeature.Instance,
		CharacterFilterRules.Instance,
		CharacterMatcher.Instance,
		CharacterPropertyDisplay.Instance,
		CharacterPropertyReferenced.Instance,
		CharacterTitle.Instance,
		Chicken.Instance,
		Choosy.Instance,
		Clothing.Instance,
		CombatConfig.Instance,
		CombatDifficulty.Instance,
		CombatEvaluation.Instance,
		CombatItemUse.Instance,
		CombatScene.Instance,
		CombatSkeleton.Instance,
		CombatSkill.Instance,
		CombatSkillProperty.Instance,
		CombatSkillType.Instance,
		CombatState.Instance,
		ConsummateLevel.Instance,
		CraftTool.Instance,
		Cricket.Instance,
		CricketParts.Instance,
		CricketPlace.Instance,
		DebateComment.Instance,
		DebateEvaluation.Instance,
		DebateNodeEffect.Instance,
		DebateRecord.Instance,
		DebateReference.Instance,
		DebateStrategy.Instance,
		DebateStrategyEffect.Instance,
		DebateStrategyTarget.Instance,
		DemandInteraction.Instance,
		DemonSlayerTrial.Instance,
		DemonSlayerTrialLevel.Instance,
		DemonSlayerTrialRestrict.Instance,
		DestinyType.Instance,
		EnemyNest.Instance,
		EquipmentEffect.Instance,
		EventActors.Instance,
		EventArgument.Instance,
		EventBoolState.Instance,
		EventConditionOperator.Instance,
		EventFunction.Instance,
		EventOptionConsumeType.Instance,
		EventScriptType.Instance,
		EventValue.Instance,
		ExtraNameText.Instance,
		FameAction.Instance,
		Feast.Instance,
		Food.Instance,
		HotKeyDisplay.Instance,
		ImplementedDlc.Instance,
		Information.Instance,
		InformationInfo.Instance,
		InformationType.Instance,
		InstantNotification.Instance,
		InteractCheck.Instance,
		InteractCheckTip.Instance,
		InteractionEventOption.Instance,
		ItemFilterRules.Instance,
		Jiao.Instance,
		JiaoNurturance.Instance,
		JiaoProperty.Instance,
		JiaoRecord.Instance,
		JieqingGameLevel.Instance,
		JieqingGamePeace.Instance,
		LandFormType.Instance,
		Legacy.Instance,
		LegacyPoint.Instance,
		LegacyPointType.Instance,
		LegendaryBookPropertyBonusType.Instance,
		LegendaryBookSlot.Instance,
		LifeLinkFeatureEffect.Instance,
		LifeRecord.Instance,
		LifeSkill.Instance,
		LifeSkillCombatEffect.Instance,
		LifeSkillCombatTalk.Instance,
		LifeSkillType.Instance,
		LoadingTips.Instance,
		Loong.Instance,
		MainStoryLineProgress.Instance,
		MakeItemSubType.Instance,
		MakeItemType.Instance,
		MapArea.Instance,
		MapBlock.Instance,
		MapBlockMatcher.Instance,
		MapPickups.Instance,
		MapState.Instance,
		Material.Instance,
		Medicine.Instance,
		Merchant.Instance,
		MerchantType.Instance,
		MiniGameYuanshan.Instance,
		MinionGroup.Instance,
		Misc.Instance,
		MixPoisonEffect.Instance,
		Month.Instance,
		MonthlyActions.Instance,
		MonthlyEvent.Instance,
		MonthlyNotification.Instance,
		MonthlyNotificationSortingGroup.Instance,
		Music.Instance,
		NeiliAllocationEffect.Instance,
		NeiliAllocationStatus.Instance,
		NeiliType.Instance,
		NormalInteraction.Instance,
		NpcRandomWords.Instance,
		Organization.Instance,
		OrganizationMember.Instance,
		OtherActionType.Instance,
		PersonalNeed.Instance,
		Poison.Instance,
		PredefinedLog.Instance,
		PrioritizedActions.Instance,
		Profession.Instance,
		ProfessionFormula.Instance,
		ProfessionSkill.Instance,
		ProtagonistFeature.Instance,
		PunishmentSeverity.Instance,
		PunishmentType.Instance,
		QiArtStrategy.Instance,
		QiDisorderEffect.Instance,
		RandomEnemy.Instance,
		RanshanGiveupLegendaryBook.Instance,
		ReadingStrategy.Instance,
		RefiningEffect.Instance,
		RelationDisplayType.Instance,
		ResourceCollection.Instance,
		ResourceType.Instance,
		SamsaraPlatformRecord.Instance,
		Season.Instance,
		SecretInformation.Instance,
		SecretInformationAppliedContent.Instance,
		SecretInformationAppliedRelation.Instance,
		SecretInformationAppliedResult.Instance,
		SecretInformationAppliedSelection.Instance,
		SecretInformationAppliedStruct.Instance,
		SecretInformationDissemination.Instance,
		SecretInformationEffect.Instance,
		SecretInformationSectPunish.Instance,
		SecretInformationSpecialCondition.Instance,
		SectApprovingEffect.Instance,
		SensitiveWords.Instance,
		SettlementPrisonEventEffect.Instance,
		SettlementPrisonRecord.Instance,
		SettlementTreasuryEventEffect.Instance,
		SettlementTreasuryRecord.Instance,
		ShopEvent.Instance,
		SkillBook.Instance,
		SkillBreakBonusEffect.Instance,
		SkillBreakBonusEffectImplement.Instance,
		SkillBreakEffectDisplay.Instance,
		SkillBreakGridList.Instance,
		SkillBreakGridType.Instance,
		SkillBreakOutlineEffect.Instance,
		SkillBreakPageEffect.Instance,
		SkillBreakPageEffectImplement.Instance,
		SkillBreakPlate.Instance,
		SkillBreakPlateGridBonusType.Instance,
		SkillGradeData.Instance,
		SolarTerm.Instance,
		SpecialEffect.Instance,
		SpecialEffectDataField.Instance,
		StoryScroll.Instance,
		SwordTomb.Instance,
		TaiwuBeHuntedEvent.Instance,
		TaiwuVillageStoragesRecord.Instance,
		TaskChain.Instance,
		TaskCondition.Instance,
		TaskHint.Instance,
		TaskInfo.Instance,
		TeaHorseCaravanEvent.Instance,
		TeaHorseCaravanTerrain.Instance,
		TeaHorseCaravanWeather.Instance,
		TeaWine.Instance,
		TeammateBubble.Instance,
		TeammateCommand.Instance,
		TravelSkeleton.Instance,
		TravelingEvent.Instance,
		TrickType.Instance,
		TutorialChapters.Instance,
		TutorialVideo.Instance,
		UpdateLog.Instance,
		VillagerRole.Instance,
		VillagerRoleArrangement.Instance,
		VillagerRoleAutoAction.Instance,
		VillagerRoleFormula.Instance,
		Weapon.Instance,
		WeaponUnlockEffect.Instance,
		WesternRegion.Instance,
		WorldCreation.Instance,
		WorldCreationGroup.Instance,
		WorldFavorability.Instance,
		WorldResource.Instance,
		WorldState.Instance,
		WugKing.Instance,
		ZhujianCombatSkillToWeapon.Instance,
		GlobalConfig.Instance
	};

	public static readonly Dictionary<string, IConfigData> NameMap = new Dictionary<string, IConfigData>
	{
		{
			"LocalSurnames",
			LocalSurnames.Instance
		},
		{
			"LocalNames",
			LocalNames.Instance
		},
		{
			"LocalZangNames",
			LocalZangNames.Instance
		},
		{
			"LocalTownNames",
			LocalTownNames.Instance
		},
		{
			"LocalMonasticTitles",
			LocalMonasticTitles.Instance
		},
		{
			"Accessory",
			Accessory.Instance
		},
		{
			"Adventure",
			Adventure.Instance
		},
		{
			"AdventureItemDropRate",
			AdventureItemDropRate.Instance
		},
		{
			"AdventureLifeSkillRequirement",
			AdventureLifeSkillRequirement.Instance
		},
		{
			"AdventureRemakeMapBlock",
			AdventureRemakeMapBlock.Instance
		},
		{
			"AdventureTerrain",
			AdventureTerrain.Instance
		},
		{
			"AdventureType",
			AdventureType.Instance
		},
		{
			"AgeEffect",
			AgeEffect.Instance
		},
		{
			"AiAction",
			AiAction.Instance
		},
		{
			"AiCondition",
			AiCondition.Instance
		},
		{
			"AiData",
			AiData.Instance
		},
		{
			"AiGroup",
			AiGroup.Instance
		},
		{
			"AiNode",
			AiNode.Instance
		},
		{
			"AiParam",
			AiParam.Instance
		},
		{
			"AiRelations",
			AiRelations.Instance
		},
		{
			"Animal",
			Animal.Instance
		},
		{
			"Armor",
			Armor.Instance
		},
		{
			"AvatarClothColors",
			AvatarClothColors.Instance
		},
		{
			"AvatarElements",
			AvatarElements.Instance
		},
		{
			"AvatarExtraParts",
			AvatarExtraParts.Instance
		},
		{
			"AvatarEyeballColors",
			AvatarEyeballColors.Instance
		},
		{
			"AvatarFeatureColors",
			AvatarFeatureColors.Instance
		},
		{
			"AvatarHairColors",
			AvatarHairColors.Instance
		},
		{
			"AvatarHead",
			AvatarHead.Instance
		},
		{
			"AvatarLipColors",
			AvatarLipColors.Instance
		},
		{
			"AvatarSkinColors",
			AvatarSkinColors.Instance
		},
		{
			"BecomeEnemyType",
			BecomeEnemyType.Instance
		},
		{
			"BehaviorType",
			BehaviorType.Instance
		},
		{
			"BigEventKey",
			BigEventKey.Instance
		},
		{
			"BodyPart",
			BodyPart.Instance
		},
		{
			"Boss",
			Boss.Instance
		},
		{
			"BuildingBlock",
			BuildingBlock.Instance
		},
		{
			"BuildingFormula",
			BuildingFormula.Instance
		},
		{
			"BuildingScale",
			BuildingScale.Instance
		},
		{
			"Carrier",
			Carrier.Instance
		},
		{
			"CatchThiefLevel",
			CatchThiefLevel.Instance
		},
		{
			"CatchThiefPlace",
			CatchThiefPlace.Instance
		},
		{
			"Character",
			Character.Instance
		},
		{
			"CharacterDeathType",
			CharacterDeathType.Instance
		},
		{
			"CharacterFeature",
			CharacterFeature.Instance
		},
		{
			"CharacterFilterRules",
			CharacterFilterRules.Instance
		},
		{
			"CharacterMatcher",
			CharacterMatcher.Instance
		},
		{
			"CharacterPropertyDisplay",
			CharacterPropertyDisplay.Instance
		},
		{
			"CharacterPropertyReferenced",
			CharacterPropertyReferenced.Instance
		},
		{
			"CharacterTitle",
			CharacterTitle.Instance
		},
		{
			"Chicken",
			Chicken.Instance
		},
		{
			"Choosy",
			Choosy.Instance
		},
		{
			"Clothing",
			Clothing.Instance
		},
		{
			"CombatConfig",
			CombatConfig.Instance
		},
		{
			"CombatDifficulty",
			CombatDifficulty.Instance
		},
		{
			"CombatEvaluation",
			CombatEvaluation.Instance
		},
		{
			"CombatItemUse",
			CombatItemUse.Instance
		},
		{
			"CombatScene",
			CombatScene.Instance
		},
		{
			"CombatSkeleton",
			CombatSkeleton.Instance
		},
		{
			"CombatSkill",
			CombatSkill.Instance
		},
		{
			"CombatSkillProperty",
			CombatSkillProperty.Instance
		},
		{
			"CombatSkillType",
			CombatSkillType.Instance
		},
		{
			"CombatState",
			CombatState.Instance
		},
		{
			"ConsummateLevel",
			ConsummateLevel.Instance
		},
		{
			"CraftTool",
			CraftTool.Instance
		},
		{
			"Cricket",
			Cricket.Instance
		},
		{
			"CricketParts",
			CricketParts.Instance
		},
		{
			"CricketPlace",
			CricketPlace.Instance
		},
		{
			"DebateComment",
			DebateComment.Instance
		},
		{
			"DebateEvaluation",
			DebateEvaluation.Instance
		},
		{
			"DebateNodeEffect",
			DebateNodeEffect.Instance
		},
		{
			"DebateRecord",
			DebateRecord.Instance
		},
		{
			"DebateReference",
			DebateReference.Instance
		},
		{
			"DebateStrategy",
			DebateStrategy.Instance
		},
		{
			"DebateStrategyEffect",
			DebateStrategyEffect.Instance
		},
		{
			"DebateStrategyTarget",
			DebateStrategyTarget.Instance
		},
		{
			"DemandInteraction",
			DemandInteraction.Instance
		},
		{
			"DemonSlayerTrial",
			DemonSlayerTrial.Instance
		},
		{
			"DemonSlayerTrialLevel",
			DemonSlayerTrialLevel.Instance
		},
		{
			"DemonSlayerTrialRestrict",
			DemonSlayerTrialRestrict.Instance
		},
		{
			"DestinyType",
			DestinyType.Instance
		},
		{
			"EnemyNest",
			EnemyNest.Instance
		},
		{
			"EquipmentEffect",
			EquipmentEffect.Instance
		},
		{
			"EventActors",
			EventActors.Instance
		},
		{
			"EventArgument",
			EventArgument.Instance
		},
		{
			"EventBoolState",
			EventBoolState.Instance
		},
		{
			"EventConditionOperator",
			EventConditionOperator.Instance
		},
		{
			"EventFunction",
			EventFunction.Instance
		},
		{
			"EventOptionConsumeType",
			EventOptionConsumeType.Instance
		},
		{
			"EventScriptType",
			EventScriptType.Instance
		},
		{
			"EventValue",
			EventValue.Instance
		},
		{
			"ExtraNameText",
			ExtraNameText.Instance
		},
		{
			"FameAction",
			FameAction.Instance
		},
		{
			"Feast",
			Feast.Instance
		},
		{
			"Food",
			Food.Instance
		},
		{
			"HotKeyDisplay",
			HotKeyDisplay.Instance
		},
		{
			"ImplementedDlc",
			ImplementedDlc.Instance
		},
		{
			"Information",
			Information.Instance
		},
		{
			"InformationInfo",
			InformationInfo.Instance
		},
		{
			"InformationType",
			InformationType.Instance
		},
		{
			"InstantNotification",
			InstantNotification.Instance
		},
		{
			"InteractCheck",
			InteractCheck.Instance
		},
		{
			"InteractCheckTip",
			InteractCheckTip.Instance
		},
		{
			"InteractionEventOption",
			InteractionEventOption.Instance
		},
		{
			"ItemFilterRules",
			ItemFilterRules.Instance
		},
		{
			"Jiao",
			Jiao.Instance
		},
		{
			"JiaoNurturance",
			JiaoNurturance.Instance
		},
		{
			"JiaoProperty",
			JiaoProperty.Instance
		},
		{
			"JiaoRecord",
			JiaoRecord.Instance
		},
		{
			"JieqingGameLevel",
			JieqingGameLevel.Instance
		},
		{
			"JieqingGamePeace",
			JieqingGamePeace.Instance
		},
		{
			"LandFormType",
			LandFormType.Instance
		},
		{
			"Legacy",
			Legacy.Instance
		},
		{
			"LegacyPoint",
			LegacyPoint.Instance
		},
		{
			"LegacyPointType",
			LegacyPointType.Instance
		},
		{
			"LegendaryBookPropertyBonusType",
			LegendaryBookPropertyBonusType.Instance
		},
		{
			"LegendaryBookSlot",
			LegendaryBookSlot.Instance
		},
		{
			"LifeLinkFeatureEffect",
			LifeLinkFeatureEffect.Instance
		},
		{
			"LifeRecord",
			LifeRecord.Instance
		},
		{
			"LifeSkill",
			LifeSkill.Instance
		},
		{
			"LifeSkillCombatEffect",
			LifeSkillCombatEffect.Instance
		},
		{
			"LifeSkillCombatTalk",
			LifeSkillCombatTalk.Instance
		},
		{
			"LifeSkillType",
			LifeSkillType.Instance
		},
		{
			"LoadingTips",
			LoadingTips.Instance
		},
		{
			"Loong",
			Loong.Instance
		},
		{
			"MainStoryLineProgress",
			MainStoryLineProgress.Instance
		},
		{
			"MakeItemSubType",
			MakeItemSubType.Instance
		},
		{
			"MakeItemType",
			MakeItemType.Instance
		},
		{
			"MapArea",
			MapArea.Instance
		},
		{
			"MapBlock",
			MapBlock.Instance
		},
		{
			"MapBlockMatcher",
			MapBlockMatcher.Instance
		},
		{
			"MapPickups",
			MapPickups.Instance
		},
		{
			"MapState",
			MapState.Instance
		},
		{
			"Material",
			Material.Instance
		},
		{
			"Medicine",
			Medicine.Instance
		},
		{
			"Merchant",
			Merchant.Instance
		},
		{
			"MerchantType",
			MerchantType.Instance
		},
		{
			"MiniGameYuanshan",
			MiniGameYuanshan.Instance
		},
		{
			"MinionGroup",
			MinionGroup.Instance
		},
		{
			"Misc",
			Misc.Instance
		},
		{
			"MixPoisonEffect",
			MixPoisonEffect.Instance
		},
		{
			"Month",
			Month.Instance
		},
		{
			"MonthlyActions",
			MonthlyActions.Instance
		},
		{
			"MonthlyEvent",
			MonthlyEvent.Instance
		},
		{
			"MonthlyNotification",
			MonthlyNotification.Instance
		},
		{
			"MonthlyNotificationSortingGroup",
			MonthlyNotificationSortingGroup.Instance
		},
		{
			"Music",
			Music.Instance
		},
		{
			"NeiliAllocationEffect",
			NeiliAllocationEffect.Instance
		},
		{
			"NeiliAllocationStatus",
			NeiliAllocationStatus.Instance
		},
		{
			"NeiliType",
			NeiliType.Instance
		},
		{
			"NormalInteraction",
			NormalInteraction.Instance
		},
		{
			"NpcRandomWords",
			NpcRandomWords.Instance
		},
		{
			"Organization",
			Organization.Instance
		},
		{
			"OrganizationMember",
			OrganizationMember.Instance
		},
		{
			"OtherActionType",
			OtherActionType.Instance
		},
		{
			"PersonalNeed",
			PersonalNeed.Instance
		},
		{
			"Poison",
			Poison.Instance
		},
		{
			"PredefinedLog",
			PredefinedLog.Instance
		},
		{
			"PrioritizedActions",
			PrioritizedActions.Instance
		},
		{
			"Profession",
			Profession.Instance
		},
		{
			"ProfessionFormula",
			ProfessionFormula.Instance
		},
		{
			"ProfessionSkill",
			ProfessionSkill.Instance
		},
		{
			"ProtagonistFeature",
			ProtagonistFeature.Instance
		},
		{
			"PunishmentSeverity",
			PunishmentSeverity.Instance
		},
		{
			"PunishmentType",
			PunishmentType.Instance
		},
		{
			"QiArtStrategy",
			QiArtStrategy.Instance
		},
		{
			"QiDisorderEffect",
			QiDisorderEffect.Instance
		},
		{
			"RandomEnemy",
			RandomEnemy.Instance
		},
		{
			"RanshanGiveupLegendaryBook",
			RanshanGiveupLegendaryBook.Instance
		},
		{
			"ReadingStrategy",
			ReadingStrategy.Instance
		},
		{
			"RefiningEffect",
			RefiningEffect.Instance
		},
		{
			"RelationDisplayType",
			RelationDisplayType.Instance
		},
		{
			"ResourceCollection",
			ResourceCollection.Instance
		},
		{
			"ResourceType",
			ResourceType.Instance
		},
		{
			"SamsaraPlatformRecord",
			SamsaraPlatformRecord.Instance
		},
		{
			"Season",
			Season.Instance
		},
		{
			"SecretInformation",
			SecretInformation.Instance
		},
		{
			"SecretInformationAppliedContent",
			SecretInformationAppliedContent.Instance
		},
		{
			"SecretInformationAppliedRelation",
			SecretInformationAppliedRelation.Instance
		},
		{
			"SecretInformationAppliedResult",
			SecretInformationAppliedResult.Instance
		},
		{
			"SecretInformationAppliedSelection",
			SecretInformationAppliedSelection.Instance
		},
		{
			"SecretInformationAppliedStruct",
			SecretInformationAppliedStruct.Instance
		},
		{
			"SecretInformationDissemination",
			SecretInformationDissemination.Instance
		},
		{
			"SecretInformationEffect",
			SecretInformationEffect.Instance
		},
		{
			"SecretInformationSectPunish",
			SecretInformationSectPunish.Instance
		},
		{
			"SecretInformationSpecialCondition",
			SecretInformationSpecialCondition.Instance
		},
		{
			"SectApprovingEffect",
			SectApprovingEffect.Instance
		},
		{
			"SensitiveWords",
			SensitiveWords.Instance
		},
		{
			"SettlementPrisonEventEffect",
			SettlementPrisonEventEffect.Instance
		},
		{
			"SettlementPrisonRecord",
			SettlementPrisonRecord.Instance
		},
		{
			"SettlementTreasuryEventEffect",
			SettlementTreasuryEventEffect.Instance
		},
		{
			"SettlementTreasuryRecord",
			SettlementTreasuryRecord.Instance
		},
		{
			"ShopEvent",
			ShopEvent.Instance
		},
		{
			"SkillBook",
			SkillBook.Instance
		},
		{
			"SkillBreakBonusEffect",
			SkillBreakBonusEffect.Instance
		},
		{
			"SkillBreakBonusEffectImplement",
			SkillBreakBonusEffectImplement.Instance
		},
		{
			"SkillBreakEffectDisplay",
			SkillBreakEffectDisplay.Instance
		},
		{
			"SkillBreakGridList",
			SkillBreakGridList.Instance
		},
		{
			"SkillBreakGridType",
			SkillBreakGridType.Instance
		},
		{
			"SkillBreakOutlineEffect",
			SkillBreakOutlineEffect.Instance
		},
		{
			"SkillBreakPageEffect",
			SkillBreakPageEffect.Instance
		},
		{
			"SkillBreakPageEffectImplement",
			SkillBreakPageEffectImplement.Instance
		},
		{
			"SkillBreakPlate",
			SkillBreakPlate.Instance
		},
		{
			"SkillBreakPlateGridBonusType",
			SkillBreakPlateGridBonusType.Instance
		},
		{
			"SkillGradeData",
			SkillGradeData.Instance
		},
		{
			"SolarTerm",
			SolarTerm.Instance
		},
		{
			"SpecialEffect",
			SpecialEffect.Instance
		},
		{
			"SpecialEffectDataField",
			SpecialEffectDataField.Instance
		},
		{
			"StoryScroll",
			StoryScroll.Instance
		},
		{
			"SwordTomb",
			SwordTomb.Instance
		},
		{
			"TaiwuBeHuntedEvent",
			TaiwuBeHuntedEvent.Instance
		},
		{
			"TaiwuVillageStoragesRecord",
			TaiwuVillageStoragesRecord.Instance
		},
		{
			"TaskChain",
			TaskChain.Instance
		},
		{
			"TaskCondition",
			TaskCondition.Instance
		},
		{
			"TaskHint",
			TaskHint.Instance
		},
		{
			"TaskInfo",
			TaskInfo.Instance
		},
		{
			"TeaHorseCaravanEvent",
			TeaHorseCaravanEvent.Instance
		},
		{
			"TeaHorseCaravanTerrain",
			TeaHorseCaravanTerrain.Instance
		},
		{
			"TeaHorseCaravanWeather",
			TeaHorseCaravanWeather.Instance
		},
		{
			"TeaWine",
			TeaWine.Instance
		},
		{
			"TeammateBubble",
			TeammateBubble.Instance
		},
		{
			"TeammateCommand",
			TeammateCommand.Instance
		},
		{
			"TravelSkeleton",
			TravelSkeleton.Instance
		},
		{
			"TravelingEvent",
			TravelingEvent.Instance
		},
		{
			"TrickType",
			TrickType.Instance
		},
		{
			"TutorialChapters",
			TutorialChapters.Instance
		},
		{
			"TutorialVideo",
			TutorialVideo.Instance
		},
		{
			"UpdateLog",
			UpdateLog.Instance
		},
		{
			"VillagerRole",
			VillagerRole.Instance
		},
		{
			"VillagerRoleArrangement",
			VillagerRoleArrangement.Instance
		},
		{
			"VillagerRoleAutoAction",
			VillagerRoleAutoAction.Instance
		},
		{
			"VillagerRoleFormula",
			VillagerRoleFormula.Instance
		},
		{
			"Weapon",
			Weapon.Instance
		},
		{
			"WeaponUnlockEffect",
			WeaponUnlockEffect.Instance
		},
		{
			"WesternRegion",
			WesternRegion.Instance
		},
		{
			"WorldCreation",
			WorldCreation.Instance
		},
		{
			"WorldCreationGroup",
			WorldCreationGroup.Instance
		},
		{
			"WorldFavorability",
			WorldFavorability.Instance
		},
		{
			"WorldResource",
			WorldResource.Instance
		},
		{
			"WorldState",
			WorldState.Instance
		},
		{
			"WugKing",
			WugKing.Instance
		},
		{
			"ZhujianCombatSkillToWeapon",
			ZhujianCombatSkillToWeapon.Instance
		},
		{
			"GlobalConfig",
			GlobalConfig.Instance
		}
	};
}
