using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class LocalTownNames : IConfigData
{
	public static LocalTownNames Instance = new LocalTownNames();

	public short VillageStart = 1;

	public short VillageEnd = 136;

	public short TownStart = 300;

	public short TownEnd = 435;

	public short WalledTownStart = 600;

	public short WalledTownEnd = 735;

	public TownNameItem[] TownNameCore;

	public IReadOnlyDictionary<string, int> RefNameMap
	{
		get
		{
			throw new NotImplementedException();
		}
	}

	public int GetItemId(string refName)
	{
		throw new NotImplementedException();
	}

	public int AddExtraItem(string identifier, string refName, object configItem)
	{
		throw new NotImplementedException();
	}

	public void Init()
	{
		TownNameCore = new TownNameItem[736]
		{
			null,
			new TownNameItem(1, "潢河村"),
			new TownNameItem(2, "龙化乡"),
			new TownNameItem(3, "土河村"),
			new TownNameItem(4, "青壶乡"),
			new TownNameItem(5, "竹侯乡"),
			new TownNameItem(6, "亡人村"),
			new TownNameItem(7, "沈东乡"),
			new TownNameItem(8, "檀君村"),
			new TownNameItem(9, "汉原乡"),
			new TownNameItem(10, "青池村"),
			new TownNameItem(11, "河源乡"),
			new TownNameItem(12, "候昙村"),
			new TownNameItem(13, "涂山村"),
			new TownNameItem(14, "铜陵村"),
			new TownNameItem(15, "德阳村"),
			new TownNameItem(16, "季华乡"),
			new TownNameItem(17, "雷泽乡"),
			new TownNameItem(18, "河池村"),
			new TownNameItem(19, "黑河村"),
			new TownNameItem(20, "清远乡"),
			new TownNameItem(21, "襄垣村"),
			new TownNameItem(22, "山阴乡"),
			new TownNameItem(23, "仁和村"),
			new TownNameItem(24, "新安村"),
			new TownNameItem(25, "常郭村"),
			new TownNameItem(26, "渑池村"),
			new TownNameItem(27, "寿安乡"),
			new TownNameItem(28, "阳翟村"),
			new TownNameItem(29, "许田村"),
			new TownNameItem(30, "商水乡"),
			new TownNameItem(31, "汝阴村"),
			new TownNameItem(32, "原武乡"),
			new TownNameItem(33, "新郑村"),
			new TownNameItem(34, "济源村"),
			new TownNameItem(35, "王屋乡"),
			new TownNameItem(36, "遂平乡"),
			new TownNameItem(37, "宝丰村"),
			new TownNameItem(38, "罗山村"),
			new TownNameItem(39, "馆陶乡"),
			new TownNameItem(40, "清平乡"),
			new TownNameItem(41, "清丰村"),
			new TownNameItem(42, "盐山村"),
			new TownNameItem(43, "武邑乡"),
			new TownNameItem(44, "博平村"),
			new TownNameItem(45, "阳信村"),
			new TownNameItem(46, "平山乡"),
			new TownNameItem(47, "灵寿村"),
			new TownNameItem(48, "临漳村"),
			new TownNameItem(49, "曲阳村"),
			new TownNameItem(50, "龙冈村"),
			new TownNameItem(51, "内丘乡"),
			new TownNameItem(52, "乌程村"),
			new TownNameItem(53, "平恩村"),
			new TownNameItem(54, "静安村"),
			new TownNameItem(55, "束鹿乡"),
			new TownNameItem(56, "博野乡"),
			new TownNameItem(57, "石鼓村"),
			new TownNameItem(58, "灵石村"),
			new TownNameItem(59, "太谷乡"),
			new TownNameItem(60, "文水村"),
			new TownNameItem(61, "神山村"),
			new TownNameItem(62, "沁水乡"),
			new TownNameItem(63, "永康村"),
			new TownNameItem(64, "西河村"),
			new TownNameItem(65, "宁化乡"),
			new TownNameItem(66, "临泉村"),
			new TownNameItem(67, "蓝田乡"),
			new TownNameItem(68, "慈溪乡"),
			new TownNameItem(69, "万泉村"),
			new TownNameItem(70, "闻喜村"),
			new TownNameItem(71, "晋陵村"),
			new TownNameItem(72, "白水村"),
			new TownNameItem(73, "富平乡"),
			new TownNameItem(74, "瑞安村"),
			new TownNameItem(75, "甘泉村"),
			new TownNameItem(76, "扶风乡"),
			new TownNameItem(77, "灵台村"),
			new TownNameItem(78, "临泾乡"),
			new TownNameItem(79, "天台乡"),
			new TownNameItem(80, "大潭村"),
			new TownNameItem(81, "兰泉乡"),
			new TownNameItem(82, "松阳村"),
			new TownNameItem(83, "临涣乡"),
			new TownNameItem(84, "宝应村"),
			new TownNameItem(85, "兴化乡"),
			new TownNameItem(86, "盈川村"),
			new TownNameItem(87, "安丰村"),
			new TownNameItem(88, "黄梅乡"),
			new TownNameItem(89, "望江村"),
			new TownNameItem(90, "无为乡"),
			new TownNameItem(91, "南陵村"),
			new TownNameItem(92, "贵池乡"),
			new TownNameItem(93, "安仁村"),
			new TownNameItem(94, "玉山乡"),
			new TownNameItem(95, "遂安村"),
			new TownNameItem(96, "龙南乡"),
			new TownNameItem(97, "太和村"),
			new TownNameItem(98, "万安村"),
			new TownNameItem(99, "禹城乡"),
			new TownNameItem(100, "忆兰乡"),
			new TownNameItem(101, "石首村"),
			new TownNameItem(102, "章丘村"),
			new TownNameItem(103, "云梦乡"),
			new TownNameItem(104, "巴陵村"),
			new TownNameItem(105, "兴山村"),
			new TownNameItem(106, "沅陵乡"),
			new TownNameItem(107, "麻阳村"),
			new TownNameItem(108, "长林乡"),
			new TownNameItem(109, "寿光村"),
			new TownNameItem(110, "善化村"),
			new TownNameItem(111, "古田村"),
			new TownNameItem(112, "龙岩村"),
			new TownNameItem(113, "华阳村"),
			new TownNameItem(114, "文登村"),
			new TownNameItem(115, "青神乡"),
			new TownNameItem(116, "青城乡"),
			new TownNameItem(117, "资阳村"),
			new TownNameItem(118, "赤水乡"),
			new TownNameItem(119, "邹平乡"),
			new TownNameItem(120, "昭化村"),
			new TownNameItem(121, "清川乡"),
			new TownNameItem(122, "襄邑村"),
			new TownNameItem(123, "巫水乡"),
			new TownNameItem(124, "钜野村"),
			new TownNameItem(125, "云安乡"),
			new TownNameItem(126, "隆化村"),
			new TownNameItem(127, "寿张村"),
			new TownNameItem(128, "翁源村"),
			new TownNameItem(129, "宣化乡"),
			new TownNameItem(130, "天河村"),
			new TownNameItem(131, "玉田村"),
			new TownNameItem(132, "瑶树乡"),
			new TownNameItem(133, "白河村"),
			new TownNameItem(134, "元武乡"),
			new TownNameItem(135, "石桥村"),
			new TownNameItem(136, "安乐乡"),
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			new TownNameItem(300, "阳乐镇"),
			new TownNameItem(301, "鸿鹄驿"),
			new TownNameItem(302, "松岳镇"),
			new TownNameItem(303, "南苏镇"),
			new TownNameItem(304, "万善镇"),
			new TownNameItem(305, "马迳镇"),
			new TownNameItem(306, "云阳镇"),
			new TownNameItem(307, "太平驿"),
			new TownNameItem(308, "长垣镇"),
			new TownNameItem(309, "凤翔镇"),
			new TownNameItem(310, "乐平镇"),
			new TownNameItem(311, "正阳镇"),
			new TownNameItem(312, "白马镇"),
			new TownNameItem(313, "乐昌镇"),
			new TownNameItem(314, "白沟镇"),
			new TownNameItem(315, "当涂镇"),
			new TownNameItem(316, "阴平镇"),
			new TownNameItem(317, "灵丘镇"),
			new TownNameItem(318, "寿阳镇"),
			new TownNameItem(319, "汾阳镇"),
			new TownNameItem(320, "陈桥驿"),
			new TownNameItem(321, "宜章镇"),
			new TownNameItem(322, "青阳镇"),
			new TownNameItem(323, "偃师镇"),
			new TownNameItem(324, "枞阳镇"),
			new TownNameItem(325, "金堂驿"),
			new TownNameItem(326, "星轺镇"),
			new TownNameItem(327, "高平镇"),
			new TownNameItem(328, "永宁镇"),
			new TownNameItem(329, "望喜镇"),
			new TownNameItem(330, "舞阳驿"),
			new TownNameItem(331, "彭泽镇"),
			new TownNameItem(332, "虞城驿"),
			new TownNameItem(333, "泰和镇"),
			new TownNameItem(334, "朱仙镇"),
			new TownNameItem(335, "景德镇"),
			new TownNameItem(336, "锦溪镇"),
			new TownNameItem(337, "会稽镇"),
			new TownNameItem(338, "荥阳驿"),
			new TownNameItem(339, "馀姚镇"),
			new TownNameItem(340, "上虞镇"),
			new TownNameItem(341, "萧山镇"),
			new TownNameItem(342, "乐陵镇"),
			new TownNameItem(343, "钱塘镇"),
			new TownNameItem(344, "高唐镇"),
			new TownNameItem(345, "乾宁镇"),
			new TownNameItem(346, "馀杭镇"),
			new TownNameItem(347, "临安镇"),
			new TownNameItem(348, "富阳镇"),
			new TownNameItem(349, "新乐驿"),
			new TownNameItem(350, "昌化镇"),
			new TownNameItem(351, "昭德镇"),
			new TownNameItem(352, "黎阳镇"),
			new TownNameItem(353, "昆山镇"),
			new TownNameItem(354, "肥乡驿"),
			new TownNameItem(355, "吴江驿"),
			new TownNameItem(356, "安肃驿"),
			new TownNameItem(357, "金坛镇"),
			new TownNameItem(358, "丹阳镇"),
			new TownNameItem(359, "阳曲镇"),
			new TownNameItem(360, "归安镇"),
			new TownNameItem(361, "安吉镇"),
			new TownNameItem(362, "永利镇"),
			new TownNameItem(363, "德清镇"),
			new TownNameItem(364, "武康镇"),
			new TownNameItem(365, "岚谷驿"),
			new TownNameItem(366, "义乌镇"),
			new TownNameItem(367, "荣河驿"),
			new TownNameItem(368, "武义镇"),
			new TownNameItem(369, "丰阳镇"),
			new TownNameItem(370, "兰溪镇"),
			new TownNameItem(371, "东阳镇"),
			new TownNameItem(372, "奉化镇"),
			new TownNameItem(373, "安化镇"),
			new TownNameItem(374, "同谷镇"),
			new TownNameItem(375, "象山镇"),
			new TownNameItem(376, "昌国镇"),
			new TownNameItem(377, "丰义镇"),
			new TownNameItem(378, "宁远镇"),
			new TownNameItem(379, "宜兴镇"),
			new TownNameItem(380, "无锡镇"),
			new TownNameItem(381, "蒙城驿"),
			new TownNameItem(382, "平阳镇"),
			new TownNameItem(383, "山阳驿"),
			new TownNameItem(384, "乐清镇"),
			new TownNameItem(385, "黄岩镇"),
			new TownNameItem(386, "来安镇"),
			new TownNameItem(387, "高邮镇"),
			new TownNameItem(388, "仙居镇"),
			new TownNameItem(389, "剑川镇"),
			new TownNameItem(390, "罗田镇"),
			new TownNameItem(391, "上元驿"),
			new TownNameItem(392, "缙云镇"),
			new TownNameItem(393, "青田镇"),
			new TownNameItem(394, "江山镇"),
			new TownNameItem(395, "奉新驿"),
			new TownNameItem(396, "常山镇"),
			new TownNameItem(397, "开化镇"),
			new TownNameItem(398, "丰城驿"),
			new TownNameItem(399, "桐庐镇"),
			new TownNameItem(400, "分水镇"),
			new TownNameItem(401, "咸宁驿"),
			new TownNameItem(402, "寿昌镇"),
			new TownNameItem(403, "临湘驿"),
			new TownNameItem(404, "华亭驿"),
			new TownNameItem(405, "崇德镇"),
			new TownNameItem(406, "嘉兴镇"),
			new TownNameItem(407, "卢阳驿"),
			new TownNameItem(408, "长清镇"),
			new TownNameItem(409, "常宁驿"),
			new TownNameItem(410, "临济镇"),
			new TownNameItem(411, "连江驿"),
			new TownNameItem(412, "千乘镇"),
			new TownNameItem(413, "临淄镇"),
			new TownNameItem(414, "灵泉驿"),
			new TownNameItem(415, "沂水镇"),
			new TownNameItem(416, "新泰镇"),
			new TownNameItem(417, "龙游驿"),
			new TownNameItem(418, "牟平驿"),
			new TownNameItem(419, "莱阳镇"),
			new TownNameItem(420, "真符驿"),
			new TownNameItem(421, "昌乐镇"),
			new TownNameItem(422, "长山镇"),
			new TownNameItem(423, "伏虞驿"),
			new TownNameItem(424, "高苑镇"),
			new TownNameItem(425, "涪陵镇"),
			new TownNameItem(426, "定陶镇"),
			new TownNameItem(427, "信安驿"),
			new TownNameItem(428, "鱼台镇"),
			new TownNameItem(429, "成武驿"),
			new TownNameItem(430, "武仙镇"),
			new TownNameItem(431, "金乡驿"),
			new TownNameItem(432, "香河驿"),
			new TownNameItem(433, "中都镇"),
			new TownNameItem(434, "三阳驿"),
			new TownNameItem(435, "仙宫驿"),
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			new TownNameItem(600, "万仞砦"),
			new TownNameItem(601, "高阳关"),
			new TownNameItem(602, "瓦桥关"),
			new TownNameItem(603, "益津关"),
			new TownNameItem(604, "三泉砦"),
			new TownNameItem(605, "大会寨"),
			new TownNameItem(606, "大散关"),
			new TownNameItem(607, "井陉口"),
			new TownNameItem(608, "太岳关"),
			new TownNameItem(609, "杀熊寨"),
			new TownNameItem(610, "青疆寨"),
			new TownNameItem(611, "抱腹山"),
			new TownNameItem(612, "采石口"),
			new TownNameItem(613, "金山寨"),
			new TownNameItem(614, "清流关"),
			new TownNameItem(615, "斜谷寨"),
			new TownNameItem(616, "静阳寨"),
			new TownNameItem(617, "镇宁口"),
			new TownNameItem(618, "燕子砦"),
			new TownNameItem(619, "新昌寨"),
			new TownNameItem(620, "长洲寨"),
			new TownNameItem(621, "丹徒口"),
			new TownNameItem(622, "青梅寨"),
			new TownNameItem(623, "白狮寨"),
			new TownNameItem(624, "颍阳口"),
			new TownNameItem(625, "伊阳寨"),
			new TownNameItem(626, "长水口"),
			new TownNameItem(627, "望陵关"),
			new TownNameItem(628, "宛丘口"),
			new TownNameItem(629, "项城关"),
			new TownNameItem(630, "西华寨"),
			new TownNameItem(631, "白马寨"),
			new TownNameItem(632, "灵河口"),
			new TownNameItem(633, "汜水砦"),
			new TownNameItem(634, "汝阳寨"),
			new TownNameItem(635, "真阳关"),
			new TownNameItem(636, "钟山寨"),
			new TownNameItem(637, "成安口"),
			new TownNameItem(638, "夏津口"),
			new TownNameItem(639, "宗城砦"),
			new TownNameItem(640, "临河寨"),
			new TownNameItem(641, "乐寿砦"),
			new TownNameItem(642, "南皮口"),
			new TownNameItem(643, "商河寨"),
			new TownNameItem(644, "任丘口"),
			new TownNameItem(645, "文安寨"),
			new TownNameItem(646, "安阳关"),
			new TownNameItem(647, "汤阴寨"),
			new TownNameItem(648, "望都口"),
			new TownNameItem(649, "沙河寨"),
			new TownNameItem(650, "南和寨"),
			new TownNameItem(651, "钜鹿关"),
			new TownNameItem(652, "武陟关"),
			new TownNameItem(653, "永年寨"),
			new TownNameItem(654, "鸡泽关"),
			new TownNameItem(655, "长兴寨"),
			new TownNameItem(656, "雁门寨"),
			new TownNameItem(657, "细腰寨"),
			new TownNameItem(658, "飞鸢寨"),
			new TownNameItem(659, "百胜寨"),
			new TownNameItem(660, "浦江口"),
			new TownNameItem(661, "赤塘关"),
			new TownNameItem(662, "大通寨"),
			new TownNameItem(663, "翼城口"),
			new TownNameItem(664, "定海砦"),
			new TownNameItem(665, "平夷口"),
			new TownNameItem(666, "石楼寨"),
			new TownNameItem(667, "龙门寨"),
			new TownNameItem(668, "武进关"),
			new TownNameItem(669, "灵宝寨"),
			new TownNameItem(670, "朱阳关"),
			new TownNameItem(671, "三原寨"),
			new TownNameItem(672, "临真口"),
			new TownNameItem(673, "江阴寨"),
			new TownNameItem(674, "通远关"),
			new TownNameItem(675, "天兴寨"),
			new TownNameItem(676, "普润砦"),
			new TownNameItem(677, "宁海寨"),
			new TownNameItem(678, "长武砦"),
			new TownNameItem(679, "鹿邑关"),
			new TownNameItem(680, "遂昌口"),
			new TownNameItem(681, "符离口"),
			new TownNameItem(682, "灵壁关"),
			new TownNameItem(683, "海陵关"),
			new TownNameItem(684, "泰兴寨"),
			new TownNameItem(685, "六合寨"),
			new TownNameItem(686, "淳化口"),
			new TownNameItem(687, "六安寨"),
			new TownNameItem(688, "怀宁寨"),
			new TownNameItem(689, "同安口"),
			new TownNameItem(690, "江宁口"),
			new TownNameItem(691, "德兴寨"),
			new TownNameItem(692, "会昌口"),
			new TownNameItem(693, "瑞金寨"),
			new TownNameItem(694, "庐陵寨"),
			new TownNameItem(695, "龙泉关"),
			new TownNameItem(696, "宜春口"),
			new TownNameItem(697, "金溪寨"),
			new TownNameItem(698, "崇阳关"),
			new TownNameItem(699, "景陵寨"),
			new TownNameItem(700, "玉沙口"),
			new TownNameItem(701, "临邑关"),
			new TownNameItem(702, "石门寨"),
			new TownNameItem(703, "秭归口"),
			new TownNameItem(704, "巴东寨"),
			new TownNameItem(705, "辰溪寨"),
			new TownNameItem(706, "渠阳口"),
			new TownNameItem(707, "当阳口"),
			new TownNameItem(708, "安仁寨"),
			new TownNameItem(709, "安丘砦"),
			new TownNameItem(710, "福清寨"),
			new TownNameItem(711, "仙游寨"),
			new TownNameItem(712, "即墨口"),
			new TownNameItem(713, "广都寨"),
			new TownNameItem(714, "盐泉口"),
			new TownNameItem(715, "火井寨"),
			new TownNameItem(716, "宿迁寨"),
			new TownNameItem(717, "青石寨"),
			new TownNameItem(718, "应灵寨"),
			new TownNameItem(719, "岳池关"),
			new TownNameItem(720, "宝丰寨"),
			new TownNameItem(721, "绵谷关"),
			new TownNameItem(722, "江油寨"),
			new TownNameItem(723, "巴渠口"),
			new TownNameItem(724, "东阿寨"),
			new TownNameItem(725, "归善砦"),
			new TownNameItem(726, "新会口"),
			new TownNameItem(727, "连山寨"),
			new TownNameItem(728, "灵川寨"),
			new TownNameItem(729, "龙平口"),
			new TownNameItem(730, "黄猿寨"),
			new TownNameItem(731, "黑狗寨"),
			new TownNameItem(732, "七圣口"),
			new TownNameItem(733, "紫绶关"),
			new TownNameItem(734, "长禄寨"),
			new TownNameItem(735, "天宁寨")
		};
	}
}
