using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class LocalMonasticTitles : IConfigData
{
	public static LocalMonasticTitles Instance = new LocalMonasticTitles();

	public short SeniorityShaolinStart;

	public short SeniorityShaolinEnd = 69;

	public short SeniorityEmeiStart = 200;

	public short SeniorityEmeiEnd = 247;

	public short SeniorityWudangStart = 400;

	public short SeniorityWudangEnd = 455;

	public short SeniorityRanshanStart = 600;

	public short SeniorityRanshanEnd = 699;

	public short SuffixBuddhistStart = 800;

	public short SuffixBuddhistEnd = 1120;

	public short SuffixTaoistStart = 1500;

	public short SuffixTaoistEnd = 1951;

	public MonasticTitleItem[] MonasticTitles;

	public IReadOnlyDictionary<string, int> RefNameMap
	{
		get
		{
			throw new NotImplementedException();
		}
	}

	public int GetItemId(string refName)
	{
		throw new NotImplementedException();
	}

	public int AddExtraItem(string identifier, string refName, object configItem)
	{
		throw new NotImplementedException();
	}

	public void Init()
	{
		MonasticTitles = new MonasticTitleItem[1952]
		{
			new MonasticTitleItem(0, "福"),
			new MonasticTitleItem(1, "慧"),
			new MonasticTitleItem(2, "智"),
			new MonasticTitleItem(3, "子"),
			new MonasticTitleItem(4, "觉"),
			new MonasticTitleItem(5, "了"),
			new MonasticTitleItem(6, "本"),
			new MonasticTitleItem(7, "圆"),
			new MonasticTitleItem(8, "可"),
			new MonasticTitleItem(9, "悟"),
			new MonasticTitleItem(10, "周"),
			new MonasticTitleItem(11, "洪"),
			new MonasticTitleItem(12, "普"),
			new MonasticTitleItem(13, "广"),
			new MonasticTitleItem(14, "宗"),
			new MonasticTitleItem(15, "道"),
			new MonasticTitleItem(16, "庆"),
			new MonasticTitleItem(17, "同"),
			new MonasticTitleItem(18, "玄"),
			new MonasticTitleItem(19, "祖"),
			new MonasticTitleItem(20, "清"),
			new MonasticTitleItem(21, "净"),
			new MonasticTitleItem(22, "真"),
			new MonasticTitleItem(23, "如"),
			new MonasticTitleItem(24, "海"),
			new MonasticTitleItem(25, "湛"),
			new MonasticTitleItem(26, "寂"),
			new MonasticTitleItem(27, "淳"),
			new MonasticTitleItem(28, "贞"),
			new MonasticTitleItem(29, "素"),
			new MonasticTitleItem(30, "德"),
			new MonasticTitleItem(31, "行"),
			new MonasticTitleItem(32, "永"),
			new MonasticTitleItem(33, "延"),
			new MonasticTitleItem(34, "恒"),
			new MonasticTitleItem(35, "妙"),
			new MonasticTitleItem(36, "体"),
			new MonasticTitleItem(37, "常"),
			new MonasticTitleItem(38, "坚"),
			new MonasticTitleItem(39, "固"),
			new MonasticTitleItem(40, "心"),
			new MonasticTitleItem(41, "朗"),
			new MonasticTitleItem(42, "照"),
			new MonasticTitleItem(43, "幽"),
			new MonasticTitleItem(44, "深"),
			new MonasticTitleItem(45, "性"),
			new MonasticTitleItem(46, "明"),
			new MonasticTitleItem(47, "鉴"),
			new MonasticTitleItem(48, "崇"),
			new MonasticTitleItem(49, "祚"),
			new MonasticTitleItem(50, "衷"),
			new MonasticTitleItem(51, "正"),
			new MonasticTitleItem(52, "善"),
			new MonasticTitleItem(53, "喜"),
			new MonasticTitleItem(54, "祥"),
			new MonasticTitleItem(55, "谨"),
			new MonasticTitleItem(56, "悫"),
			new MonasticTitleItem(57, "原"),
			new MonasticTitleItem(58, "济"),
			new MonasticTitleItem(59, "度"),
			new MonasticTitleItem(60, "雪"),
			new MonasticTitleItem(61, "庭"),
			new MonasticTitleItem(62, "为"),
			new MonasticTitleItem(63, "导"),
			new MonasticTitleItem(64, "师"),
			new MonasticTitleItem(65, "引"),
			new MonasticTitleItem(66, "汝"),
			new MonasticTitleItem(67, "归"),
			new MonasticTitleItem(68, "铉"),
			new MonasticTitleItem(69, "路"),
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			new MonasticTitleItem(200, "智"),
			new MonasticTitleItem(201, "慧"),
			new MonasticTitleItem(202, "清"),
			new MonasticTitleItem(203, "静"),
			new MonasticTitleItem(204, "道"),
			new MonasticTitleItem(205, "德"),
			new MonasticTitleItem(206, "圆"),
			new MonasticTitleItem(207, "明"),
			new MonasticTitleItem(208, "真"),
			new MonasticTitleItem(209, "如"),
			new MonasticTitleItem(210, "性"),
			new MonasticTitleItem(211, "海"),
			new MonasticTitleItem(212, "寂"),
			new MonasticTitleItem(213, "照"),
			new MonasticTitleItem(214, "普"),
			new MonasticTitleItem(215, "通"),
			new MonasticTitleItem(216, "心"),
			new MonasticTitleItem(217, "源"),
			new MonasticTitleItem(218, "广"),
			new MonasticTitleItem(219, "续"),
			new MonasticTitleItem(220, "本"),
			new MonasticTitleItem(221, "觉"),
			new MonasticTitleItem(222, "昌"),
			new MonasticTitleItem(223, "隆"),
			new MonasticTitleItem(224, "能"),
			new MonasticTitleItem(225, "仁"),
			new MonasticTitleItem(226, "圣"),
			new MonasticTitleItem(227, "果"),
			new MonasticTitleItem(228, "常"),
			new MonasticTitleItem(229, "演"),
			new MonasticTitleItem(230, "宽"),
			new MonasticTitleItem(231, "宏"),
			new MonasticTitleItem(232, "惟"),
			new MonasticTitleItem(233, "传"),
			new MonasticTitleItem(234, "法"),
			new MonasticTitleItem(235, "印"),
			new MonasticTitleItem(236, "正"),
			new MonasticTitleItem(237, "悟"),
			new MonasticTitleItem(238, "会"),
			new MonasticTitleItem(239, "融"),
			new MonasticTitleItem(240, "坚"),
			new MonasticTitleItem(241, "持"),
			new MonasticTitleItem(242, "戒"),
			new MonasticTitleItem(243, "定"),
			new MonasticTitleItem(244, "永"),
			new MonasticTitleItem(245, "继"),
			new MonasticTitleItem(246, "祖"),
			new MonasticTitleItem(247, "宗"),
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			new MonasticTitleItem(400, "玄"),
			new MonasticTitleItem(401, "元"),
			new MonasticTitleItem(402, "通"),
			new MonasticTitleItem(403, "道"),
			new MonasticTitleItem(404, "居"),
			new MonasticTitleItem(405, "端"),
			new MonasticTitleItem(406, "静"),
			new MonasticTitleItem(407, "白"),
			new MonasticTitleItem(408, "鹤"),
			new MonasticTitleItem(409, "乘"),
			new MonasticTitleItem(410, "虚"),
			new MonasticTitleItem(411, "向"),
			new MonasticTitleItem(412, "自"),
			new MonasticTitleItem(413, "清"),
			new MonasticTitleItem(414, "师"),
			new MonasticTitleItem(415, "资"),
			new MonasticTitleItem(416, "月"),
			new MonasticTitleItem(417, "圆"),
			new MonasticTitleItem(418, "皈"),
			new MonasticTitleItem(419, "志"),
			new MonasticTitleItem(420, "礼"),
			new MonasticTitleItem(421, "身"),
			new MonasticTitleItem(422, "中"),
			new MonasticTitleItem(423, "抱"),
			new MonasticTitleItem(424, "一"),
			new MonasticTitleItem(425, "管"),
			new MonasticTitleItem(426, "丹"),
			new MonasticTitleItem(427, "成"),
			new MonasticTitleItem(428, "太"),
			new MonasticTitleItem(429, "上"),
			new MonasticTitleItem(430, "渊"),
			new MonasticTitleItem(431, "微"),
			new MonasticTitleItem(432, "入"),
			new MonasticTitleItem(433, "妙"),
			new MonasticTitleItem(434, "园"),
			new MonasticTitleItem(435, "凌"),
			new MonasticTitleItem(436, "云"),
			new MonasticTitleItem(437, "星"),
			new MonasticTitleItem(438, "朗"),
			new MonasticTitleItem(439, "贮"),
			new MonasticTitleItem(440, "壶"),
			new MonasticTitleItem(441, "天"),
			new MonasticTitleItem(442, "功"),
			new MonasticTitleItem(443, "候"),
			new MonasticTitleItem(444, "到"),
			new MonasticTitleItem(445, "日"),
			new MonasticTitleItem(446, "方"),
			new MonasticTitleItem(447, "许"),
			new MonasticTitleItem(448, "就"),
			new MonasticTitleItem(449, "始"),
			new MonasticTitleItem(450, "悟"),
			new MonasticTitleItem(451, "真"),
			new MonasticTitleItem(452, "言"),
			new MonasticTitleItem(453, "信"),
			new MonasticTitleItem(454, "可"),
			new MonasticTitleItem(455, "传"),
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			new MonasticTitleItem(600, "道"),
			new MonasticTitleItem(601, "德"),
			new MonasticTitleItem(602, "清"),
			new MonasticTitleItem(603, "高"),
			new MonasticTitleItem(604, "上"),
			new MonasticTitleItem(605, "云"),
			new MonasticTitleItem(606, "程"),
			new MonasticTitleItem(607, "守"),
			new MonasticTitleItem(608, "炼"),
			new MonasticTitleItem(609, "丹"),
			new MonasticTitleItem(610, "九"),
			new MonasticTitleItem(611, "重"),
			new MonasticTitleItem(612, "天"),
			new MonasticTitleItem(613, "外"),
			new MonasticTitleItem(614, "子"),
			new MonasticTitleItem(615, "方"),
			new MonasticTitleItem(616, "知"),
			new MonasticTitleItem(617, "妙"),
			new MonasticTitleItem(618, "中"),
			new MonasticTitleItem(619, "玄"),
			new MonasticTitleItem(620, "性"),
			new MonasticTitleItem(621, "净"),
			new MonasticTitleItem(622, "自"),
			new MonasticTitleItem(623, "然"),
			new MonasticTitleItem(624, "体"),
			new MonasticTitleItem(625, "发"),
			new MonasticTitleItem(626, "白"),
			new MonasticTitleItem(627, "面"),
			new MonasticTitleItem(628, "童"),
			new MonasticTitleItem(629, "颜"),
			new MonasticTitleItem(630, "袖"),
			new MonasticTitleItem(631, "通"),
			new MonasticTitleItem(632, "乾"),
			new MonasticTitleItem(633, "坤"),
			new MonasticTitleItem(634, "大"),
			new MonasticTitleItem(635, "阴"),
			new MonasticTitleItem(636, "阳"),
			new MonasticTitleItem(637, "造"),
			new MonasticTitleItem(638, "化"),
			new MonasticTitleItem(639, "坚"),
			new MonasticTitleItem(640, "悟"),
			new MonasticTitleItem(641, "本"),
			new MonasticTitleItem(642, "崇"),
			new MonasticTitleItem(643, "正"),
			new MonasticTitleItem(644, "理"),
			new MonasticTitleItem(645, "冲"),
			new MonasticTitleItem(646, "和"),
			new MonasticTitleItem(647, "养"),
			new MonasticTitleItem(648, "太"),
			new MonasticTitleItem(649, "源"),
			new MonasticTitleItem(650, "情"),
			new MonasticTitleItem(651, "即"),
			new MonasticTitleItem(652, "金"),
			new MonasticTitleItem(653, "木"),
			new MonasticTitleItem(654, "柄"),
			new MonasticTitleItem(655, "一"),
			new MonasticTitleItem(656, "定"),
			new MonasticTitleItem(657, "龙"),
			new MonasticTitleItem(658, "虎"),
			new MonasticTitleItem(659, "蟠"),
			new MonasticTitleItem(660, "慧"),
			new MonasticTitleItem(661, "发"),
			new MonasticTitleItem(662, "祥"),
			new MonasticTitleItem(663, "光"),
			new MonasticTitleItem(664, "现"),
			new MonasticTitleItem(665, "连"),
			new MonasticTitleItem(666, "开"),
			new MonasticTitleItem(667, "宝"),
			new MonasticTitleItem(668, "叶"),
			new MonasticTitleItem(669, "鲜"),
			new MonasticTitleItem(670, "神"),
			new MonasticTitleItem(671, "凝"),
			new MonasticTitleItem(672, "归"),
			new MonasticTitleItem(673, "根"),
			new MonasticTitleItem(674, "窍"),
			new MonasticTitleItem(675, "气"),
			new MonasticTitleItem(676, "足"),
			new MonasticTitleItem(677, "复"),
			new MonasticTitleItem(678, "命"),
			new MonasticTitleItem(679, "关"),
			new MonasticTitleItem(680, "三"),
			new MonasticTitleItem(681, "千"),
			new MonasticTitleItem(682, "功"),
			new MonasticTitleItem(683, "圆"),
			new MonasticTitleItem(684, "满"),
			new MonasticTitleItem(685, "异"),
			new MonasticTitleItem(686, "姓"),
			new MonasticTitleItem(687, "合"),
			new MonasticTitleItem(688, "真"),
			new MonasticTitleItem(689, "仙"),
			new MonasticTitleItem(690, "蓬"),
			new MonasticTitleItem(691, "莱"),
			new MonasticTitleItem(692, "逍"),
			new MonasticTitleItem(693, "遥"),
			new MonasticTitleItem(694, "路"),
			new MonasticTitleItem(695, "直"),
			new MonasticTitleItem(696, "超"),
			new MonasticTitleItem(697, "玉"),
			new MonasticTitleItem(698, "京"),
			new MonasticTitleItem(699, "山"),
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			new MonasticTitleItem(800, "如"),
			new MonasticTitleItem(801, "我"),
			new MonasticTitleItem(802, "闻"),
			new MonasticTitleItem(803, "时"),
			new MonasticTitleItem(804, "舍"),
			new MonasticTitleItem(805, "祗"),
			new MonasticTitleItem(806, "树"),
			new MonasticTitleItem(807, "园"),
			new MonasticTitleItem(808, "与"),
			new MonasticTitleItem(809, "丘"),
			new MonasticTitleItem(810, "众"),
			new MonasticTitleItem(811, "世"),
			new MonasticTitleItem(812, "尊"),
			new MonasticTitleItem(813, "著"),
			new MonasticTitleItem(814, "持"),
			new MonasticTitleItem(815, "钵"),
			new MonasticTitleItem(816, "入"),
			new MonasticTitleItem(817, "乞"),
			new MonasticTitleItem(818, "于"),
			new MonasticTitleItem(819, "中"),
			new MonasticTitleItem(820, "次"),
			new MonasticTitleItem(821, "已"),
			new MonasticTitleItem(822, "还"),
			new MonasticTitleItem(823, "至"),
			new MonasticTitleItem(824, "本"),
			new MonasticTitleItem(825, "处"),
			new MonasticTitleItem(826, "讫"),
			new MonasticTitleItem(827, "座"),
			new MonasticTitleItem(828, "刚"),
			new MonasticTitleItem(829, "法"),
			new MonasticTitleItem(830, "因"),
			new MonasticTitleItem(831, "由"),
			new MonasticTitleItem(832, "善"),
			new MonasticTitleItem(833, "启"),
			new MonasticTitleItem(834, "长"),
			new MonasticTitleItem(835, "须"),
			new MonasticTitleItem(836, "即"),
			new MonasticTitleItem(837, "从"),
			new MonasticTitleItem(838, "合"),
			new MonasticTitleItem(839, "言"),
			new MonasticTitleItem(840, "有"),
			new MonasticTitleItem(841, "来"),
			new MonasticTitleItem(842, "念"),
			new MonasticTitleItem(843, "嘱"),
			new MonasticTitleItem(844, "藐"),
			new MonasticTitleItem(845, "心"),
			new MonasticTitleItem(846, "应"),
			new MonasticTitleItem(847, "云"),
			new MonasticTitleItem(848, "住"),
			new MonasticTitleItem(849, "伏"),
			new MonasticTitleItem(850, "汝"),
			new MonasticTitleItem(851, "说"),
			new MonasticTitleItem(852, "谛"),
			new MonasticTitleItem(853, "听"),
			new MonasticTitleItem(854, "为"),
			new MonasticTitleItem(855, "然"),
			new MonasticTitleItem(856, "乐"),
			new MonasticTitleItem(857, "乘"),
			new MonasticTitleItem(858, "正"),
			new MonasticTitleItem(859, "宗"),
			new MonasticTitleItem(860, "诃"),
			new MonasticTitleItem(861, "切"),
			new MonasticTitleItem(862, "化"),
			new MonasticTitleItem(863, "色"),
			new MonasticTitleItem(864, "无"),
			new MonasticTitleItem(865, "余"),
			new MonasticTitleItem(866, "灭"),
			new MonasticTitleItem(867, "渡"),
			new MonasticTitleItem(868, "实"),
			new MonasticTitleItem(869, "得"),
			new MonasticTitleItem(870, "相"),
			new MonasticTitleItem(871, "复"),
			new MonasticTitleItem(872, "行"),
			new MonasticTitleItem(873, "妙"),
			new MonasticTitleItem(874, "布"),
			new MonasticTitleItem(875, "施"),
			new MonasticTitleItem(876, "声"),
			new MonasticTitleItem(877, "德"),
			new MonasticTitleItem(878, "思"),
			new MonasticTitleItem(879, "意"),
			new MonasticTitleItem(880, "方"),
			new MonasticTitleItem(881, "虚"),
			new MonasticTitleItem(882, "空"),
			new MonasticTitleItem(883, "理"),
			new MonasticTitleItem(884, "见"),
			new MonasticTitleItem(885, "妄"),
			new MonasticTitleItem(886, "信"),
			new MonasticTitleItem(887, "章"),
			new MonasticTitleItem(888, "戒"),
			new MonasticTitleItem(889, "修"),
			new MonasticTitleItem(890, "能"),
			new MonasticTitleItem(891, "知"),
			new MonasticTitleItem(892, "根"),
			new MonasticTitleItem(893, "净"),
			new MonasticTitleItem(894, "悉"),
			new MonasticTitleItem(895, "喻"),
			new MonasticTitleItem(896, "定"),
			new MonasticTitleItem(897, "界"),
			new MonasticTitleItem(898, "宝"),
			new MonasticTitleItem(899, "用"),
			new MonasticTitleItem(900, "宁"),
			new MonasticTitleItem(901, "性"),
			new MonasticTitleItem(902, "受"),
			new MonasticTitleItem(903, "偈"),
			new MonasticTitleItem(904, "胜"),
			new MonasticTitleItem(905, "含"),
			new MonasticTitleItem(906, "诤"),
			new MonasticTitleItem(907, "昧"),
			new MonasticTitleItem(908, "离"),
			new MonasticTitleItem(909, "严"),
			new MonasticTitleItem(910, "灯"),
			new MonasticTitleItem(911, "譬"),
			new MonasticTitleItem(912, "弥"),
			new MonasticTitleItem(913, "恒"),
			new MonasticTitleItem(914, "随"),
			new MonasticTitleItem(915, "尽"),
			new MonasticTitleItem(916, "诵"),
			new MonasticTitleItem(917, "成"),
			new MonasticTitleItem(918, "奉"),
			new MonasticTitleItem(919, "微"),
			new MonasticTitleItem(920, "寂"),
			new MonasticTitleItem(921, "涕"),
			new MonasticTitleItem(922, "悲"),
			new MonasticTitleItem(923, "泣"),
			new MonasticTitleItem(924, "慧"),
			new MonasticTitleItem(925, "功"),
			new MonasticTitleItem(926, "难"),
			new MonasticTitleItem(927, "忍"),
			new MonasticTitleItem(928, "节"),
			new MonasticTitleItem(929, "支"),
			new MonasticTitleItem(930, "嗔"),
			new MonasticTitleItem(931, "益"),
			new MonasticTitleItem(932, "真"),
			new MonasticTitleItem(933, "语"),
			new MonasticTitleItem(934, "诳"),
			new MonasticTitleItem(935, "光"),
			new MonasticTitleItem(936, "明"),
			new MonasticTitleItem(937, "照"),
			new MonasticTitleItem(938, "智"),
			new MonasticTitleItem(939, "初"),
			new MonasticTitleItem(940, "劫"),
			new MonasticTitleItem(941, "广"),
			new MonasticTitleItem(942, "礼"),
			new MonasticTitleItem(943, "业"),
			new MonasticTitleItem(944, "障"),
			new MonasticTitleItem(945, "轻"),
			new MonasticTitleItem(946, "消"),
			new MonasticTitleItem(947, "承"),
			new MonasticTitleItem(948, "究"),
			new MonasticTitleItem(949, "竟"),
			new MonasticTitleItem(950, "授"),
			new MonasticTitleItem(951, "释"),
			new MonasticTitleItem(952, "通"),
			new MonasticTitleItem(953, "观"),
			new MonasticTitleItem(954, "缘"),
			new MonasticTitleItem(955, "音"),
			new MonasticTitleItem(956, "断"),
			new MonasticTitleItem(957, "梦"),
			new MonasticTitleItem(958, "幻"),
			new MonasticTitleItem(959, "露"),
			new MonasticTitleItem(960, "在"),
			new MonasticTitleItem(961, "竹"),
			new MonasticTitleItem(962, "琳"),
			new MonasticTitleItem(963, "莲"),
			new MonasticTitleItem(964, "清"),
			new MonasticTitleItem(965, "静"),
			new MonasticTitleItem(966, "圆"),
			new MonasticTitleItem(967, "融"),
			new MonasticTitleItem(968, "觉"),
			new MonasticTitleItem(969, "痴"),
			new MonasticTitleItem(970, "颠"),
			new MonasticTitleItem(971, "苦"),
			new MonasticTitleItem(972, "集"),
			new MonasticTitleItem(973, "慈"),
			new MonasticTitleItem(974, "喜"),
			new MonasticTitleItem(975, "常"),
			new MonasticTitleItem(976, "想"),
			new MonasticTitleItem(977, "识"),
			new MonasticTitleItem(978, "尘"),
			new MonasticTitleItem(979, "恕"),
			new MonasticTitleItem(980, "隅"),
			new MonasticTitleItem(981, "虑"),
			new MonasticTitleItem(982, "愧"),
			new MonasticTitleItem(983, "悔"),
			new MonasticTitleItem(984, "惭"),
			new MonasticTitleItem(985, "惧"),
			new MonasticTitleItem(986, "憎"),
			new MonasticTitleItem(987, "弃"),
			new MonasticTitleItem(988, "贤"),
			new MonasticTitleItem(989, "痛"),
			new MonasticTitleItem(990, "恸"),
			new MonasticTitleItem(991, "厄"),
			new MonasticTitleItem(992, "予"),
			new MonasticTitleItem(993, "眇"),
			new MonasticTitleItem(994, "枯"),
			new MonasticTitleItem(995, "荣"),
			new MonasticTitleItem(996, "台"),
			new MonasticTitleItem(997, "危"),
			new MonasticTitleItem(998, "灾"),
			new MonasticTitleItem(999, "谏"),
			new MonasticTitleItem(1000, "挈"),
			new MonasticTitleItem(1001, "直"),
			new MonasticTitleItem(1002, "饴"),
			new MonasticTitleItem(1003, "怡"),
			new MonasticTitleItem(1004, "是"),
			new MonasticTitleItem(1005, "若"),
			new MonasticTitleItem(1006, "卉"),
			new MonasticTitleItem(1007, "炎"),
			new MonasticTitleItem(1008, "临"),
			new MonasticTitleItem(1009, "誉"),
			new MonasticTitleItem(1010, "独"),
			new MonasticTitleItem(1011, "逝"),
			new MonasticTitleItem(1012, "羡"),
			new MonasticTitleItem(1013, "涂"),
			new MonasticTitleItem(1014, "仪"),
			new MonasticTitleItem(1015, "远"),
			new MonasticTitleItem(1016, "忧"),
			new MonasticTitleItem(1017, "训"),
			new MonasticTitleItem(1018, "衡"),
			new MonasticTitleItem(1019, "致"),
			new MonasticTitleItem(1020, "晖"),
			new MonasticTitleItem(1021, "患"),
			new MonasticTitleItem(1022, "安"),
			new MonasticTitleItem(1023, "晦"),
			new MonasticTitleItem(1024, "错"),
			new MonasticTitleItem(1025, "惟"),
			new MonasticTitleItem(1026, "衰"),
			new MonasticTitleItem(1027, "烛"),
			new MonasticTitleItem(1028, "伤"),
			new MonasticTitleItem(1029, "损"),
			new MonasticTitleItem(1030, "达"),
			new MonasticTitleItem(1031, "执"),
			new MonasticTitleItem(1032, "忘"),
			new MonasticTitleItem(1033, "殃"),
			new MonasticTitleItem(1034, "岸"),
			new MonasticTitleItem(1035, "砭"),
			new MonasticTitleItem(1036, "废"),
			new MonasticTitleItem(1037, "惑"),
			new MonasticTitleItem(1038, "焕"),
			new MonasticTitleItem(1039, "休"),
			new MonasticTitleItem(1040, "诎"),
			new MonasticTitleItem(1041, "却"),
			new MonasticTitleItem(1042, "侮"),
			new MonasticTitleItem(1043, "愿"),
			new MonasticTitleItem(1044, "介"),
			new MonasticTitleItem(1045, "治"),
			new MonasticTitleItem(1046, "证"),
			new MonasticTitleItem(1047, "逐"),
			new MonasticTitleItem(1048, "讼"),
			new MonasticTitleItem(1049, "徽"),
			new MonasticTitleItem(1050, "毁"),
			new MonasticTitleItem(1051, "逆"),
			new MonasticTitleItem(1052, "兴"),
			new MonasticTitleItem(1053, "诟"),
			new MonasticTitleItem(1054, "平"),
			new MonasticTitleItem(1055, "罔"),
			new MonasticTitleItem(1056, "病"),
			new MonasticTitleItem(1057, "雅"),
			new MonasticTitleItem(1058, "倚"),
			new MonasticTitleItem(1059, "逸"),
			new MonasticTitleItem(1060, "佚"),
			new MonasticTitleItem(1061, "愆"),
			new MonasticTitleItem(1062, "隐"),
			new MonasticTitleItem(1063, "让"),
			new MonasticTitleItem(1064, "盈"),
			new MonasticTitleItem(1065, "勉"),
			new MonasticTitleItem(1066, "洁"),
			new MonasticTitleItem(1067, "免"),
			new MonasticTitleItem(1068, "昭"),
			new MonasticTitleItem(1069, "哲"),
			new MonasticTitleItem(1070, "趣"),
			new MonasticTitleItem(1071, "诲"),
			new MonasticTitleItem(1072, "望"),
			new MonasticTitleItem(1073, "问"),
			new MonasticTitleItem(1074, "久"),
			new MonasticTitleItem(1075, "秽"),
			new MonasticTitleItem(1076, "阔"),
			new MonasticTitleItem(1077, "铄"),
			new MonasticTitleItem(1078, "仁"),
			new MonasticTitleItem(1079, "鸿"),
			new MonasticTitleItem(1080, "限"),
			new MonasticTitleItem(1081, "旅"),
			new MonasticTitleItem(1082, "仲"),
			new MonasticTitleItem(1083, "尚"),
			new MonasticTitleItem(1084, "摧"),
			new MonasticTitleItem(1085, "笃"),
			new MonasticTitleItem(1086, "取"),
			new MonasticTitleItem(1087, "秉"),
			new MonasticTitleItem(1088, "亢"),
			new MonasticTitleItem(1089, "敛"),
			new MonasticTitleItem(1090, "衍"),
			new MonasticTitleItem(1091, "悯"),
			new MonasticTitleItem(1092, "抑"),
			new MonasticTitleItem(1093, "洗"),
			new MonasticTitleItem(1094, "甫"),
			new MonasticTitleItem(1095, "学"),
			new MonasticTitleItem(1096, "纪"),
			new MonasticTitleItem(1097, "律"),
			new MonasticTitleItem(1098, "谕"),
			new MonasticTitleItem(1099, "禁"),
			new MonasticTitleItem(1100, "怠"),
			new MonasticTitleItem(1101, "恢"),
			new MonasticTitleItem(1102, "肃"),
			new MonasticTitleItem(1103, "创"),
			new MonasticTitleItem(1104, "惕"),
			new MonasticTitleItem(1105, "林"),
			new MonasticTitleItem(1106, "居"),
			new MonasticTitleItem(1107, "收"),
			new MonasticTitleItem(1108, "莳"),
			new MonasticTitleItem(1109, "伦"),
			new MonasticTitleItem(1110, "困"),
			new MonasticTitleItem(1111, "殆"),
			new MonasticTitleItem(1112, "恻"),
			new MonasticTitleItem(1113, "冢"),
			new MonasticTitleItem(1114, "孽"),
			new MonasticTitleItem(1115, "愁"),
			new MonasticTitleItem(1116, "叹"),
			new MonasticTitleItem(1117, "沌"),
			new MonasticTitleItem(1118, "恩"),
			new MonasticTitleItem(1119, "殉"),
			new MonasticTitleItem(1120, "遗"),
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			new MonasticTitleItem(1500, "玄"),
			new MonasticTitleItem(1501, "序"),
			new MonasticTitleItem(1502, "驯"),
			new MonasticTitleItem(1503, "浑"),
			new MonasticTitleItem(1504, "行"),
			new MonasticTitleItem(1505, "穷"),
			new MonasticTitleItem(1506, "正"),
			new MonasticTitleItem(1507, "象"),
			new MonasticTitleItem(1508, "天"),
			new MonasticTitleItem(1509, "阴"),
			new MonasticTitleItem(1510, "阳"),
			new MonasticTitleItem(1511, "以"),
			new MonasticTitleItem(1512, "一"),
			new MonasticTitleItem(1513, "乘"),
			new MonasticTitleItem(1514, "形"),
			new MonasticTitleItem(1515, "方"),
			new MonasticTitleItem(1516, "疏"),
			new MonasticTitleItem(1517, "成"),
			new MonasticTitleItem(1518, "九"),
			new MonasticTitleItem(1519, "为"),
			new MonasticTitleItem(1520, "生"),
			new MonasticTitleItem(1521, "纲"),
			new MonasticTitleItem(1522, "名"),
			new MonasticTitleItem(1523, "岁"),
			new MonasticTitleItem(1524, "咸"),
			new MonasticTitleItem(1525, "贞"),
			new MonasticTitleItem(1526, "测"),
			new MonasticTitleItem(1527, "盛"),
			new MonasticTitleItem(1528, "炳"),
			new MonasticTitleItem(1529, "明"),
			new MonasticTitleItem(1530, "离"),
			new MonasticTitleItem(1531, "章"),
			new MonasticTitleItem(1532, "淳"),
			new MonasticTitleItem(1533, "光"),
			new MonasticTitleItem(1534, "夜"),
			new MonasticTitleItem(1535, "昼"),
			new MonasticTitleItem(1536, "之"),
			new MonasticTitleItem(1537, "或"),
			new MonasticTitleItem(1538, "臧"),
			new MonasticTitleItem(1539, "福"),
			new MonasticTitleItem(1540, "升"),
			new MonasticTitleItem(1541, "幽"),
			new MonasticTitleItem(1542, "极"),
			new MonasticTitleItem(1543, "相"),
			new MonasticTitleItem(1544, "关"),
			new MonasticTitleItem(1545, "通"),
			new MonasticTitleItem(1546, "纬"),
			new MonasticTitleItem(1547, "巡"),
			new MonasticTitleItem(1548, "甲"),
			new MonasticTitleItem(1549, "斗"),
			new MonasticTitleItem(1550, "逢"),
			new MonasticTitleItem(1551, "历"),
			new MonasticTitleItem(1552, "谷"),
			new MonasticTitleItem(1553, "时"),
			new MonasticTitleItem(1554, "雍"),
			new MonasticTitleItem(1555, "中"),
			new MonasticTitleItem(1556, "潜"),
			new MonasticTitleItem(1557, "信"),
			new MonasticTitleItem(1558, "初"),
			new MonasticTitleItem(1559, "昆"),
			new MonasticTitleItem(1560, "仑"),
			new MonasticTitleItem(1561, "思"),
			new MonasticTitleItem(1562, "也"),
			new MonasticTitleItem(1563, "次"),
			new MonasticTitleItem(1564, "战"),
			new MonasticTitleItem(1565, "善"),
			new MonasticTitleItem(1566, "庸"),
			new MonasticTitleItem(1567, "见"),
			new MonasticTitleItem(1568, "造"),
			new MonasticTitleItem(1569, "虚"),
			new MonasticTitleItem(1570, "因"),
			new MonasticTitleItem(1571, "性"),
			new MonasticTitleItem(1572, "命"),
			new MonasticTitleItem(1573, "能"),
			new MonasticTitleItem(1574, "利"),
			new MonasticTitleItem(1575, "用"),
			new MonasticTitleItem(1576, "辰"),
			new MonasticTitleItem(1577, "作"),
			new MonasticTitleItem(1578, "当"),
			new MonasticTitleItem(1579, "月"),
			new MonasticTitleItem(1580, "阙"),
			new MonasticTitleItem(1581, "如"),
			new MonasticTitleItem(1582, "开"),
			new MonasticTitleItem(1583, "始"),
			new MonasticTitleItem(1584, "退"),
			new MonasticTitleItem(1585, "火"),
			new MonasticTitleItem(1586, "魁"),
			new MonasticTitleItem(1587, "颐"),
			new MonasticTitleItem(1588, "水"),
			new MonasticTitleItem(1589, "任"),
			new MonasticTitleItem(1590, "臣"),
			new MonasticTitleItem(1591, "覆"),
			new MonasticTitleItem(1592, "秋"),
			new MonasticTitleItem(1593, "常"),
			new MonasticTitleItem(1594, "失"),
			new MonasticTitleItem(1595, "德"),
			new MonasticTitleItem(1596, "颠"),
			new MonasticTitleItem(1597, "灵"),
			new MonasticTitleItem(1598, "克"),
			new MonasticTitleItem(1599, "周"),
			new MonasticTitleItem(1600, "继"),
			new MonasticTitleItem(1601, "汇"),
			new MonasticTitleItem(1602, "还"),
			new MonasticTitleItem(1603, "心"),
			new MonasticTitleItem(1604, "僭"),
			new MonasticTitleItem(1605, "枢"),
			new MonasticTitleItem(1606, "隅"),
			new MonasticTitleItem(1607, "吉"),
			new MonasticTitleItem(1608, "环"),
			new MonasticTitleItem(1609, "庐"),
			new MonasticTitleItem(1610, "厥"),
			new MonasticTitleItem(1611, "渝"),
			new MonasticTitleItem(1612, "诚"),
			new MonasticTitleItem(1613, "亨"),
			new MonasticTitleItem(1614, "丰"),
			new MonasticTitleItem(1615, "朋"),
			new MonasticTitleItem(1616, "蒙"),
			new MonasticTitleItem(1617, "从"),
			new MonasticTitleItem(1618, "躬"),
			new MonasticTitleItem(1619, "祸"),
			new MonasticTitleItem(1620, "弃"),
			new MonasticTitleItem(1621, "贤"),
			new MonasticTitleItem(1622, "微"),
			new MonasticTitleItem(1623, "纯"),
			new MonasticTitleItem(1624, "藏"),
			new MonasticTitleItem(1625, "郁"),
			new MonasticTitleItem(1626, "泉"),
			new MonasticTitleItem(1627, "化"),
			new MonasticTitleItem(1628, "屈"),
			new MonasticTitleItem(1629, "适"),
			new MonasticTitleItem(1630, "赤"),
			new MonasticTitleItem(1631, "扶"),
			new MonasticTitleItem(1632, "元"),
			new MonasticTitleItem(1633, "终"),
			new MonasticTitleItem(1634, "詹"),
			new MonasticTitleItem(1635, "堪"),
			new MonasticTitleItem(1636, "难"),
			new MonasticTitleItem(1637, "渊"),
			new MonasticTitleItem(1638, "宜"),
			new MonasticTitleItem(1639, "丘"),
			new MonasticTitleItem(1640, "得"),
			new MonasticTitleItem(1641, "登"),
			new MonasticTitleItem(1642, "代"),
			new MonasticTitleItem(1643, "轴"),
			new MonasticTitleItem(1644, "崇"),
			new MonasticTitleItem(1645, "川"),
			new MonasticTitleItem(1646, "波"),
			new MonasticTitleItem(1647, "辑"),
			new MonasticTitleItem(1648, "航"),
			new MonasticTitleItem(1649, "与"),
			new MonasticTitleItem(1650, "闲"),
			new MonasticTitleItem(1651, "然"),
			new MonasticTitleItem(1652, "伏"),
			new MonasticTitleItem(1653, "雄"),
			new MonasticTitleItem(1654, "施"),
			new MonasticTitleItem(1655, "珍"),
			new MonasticTitleItem(1656, "宝"),
			new MonasticTitleItem(1657, "舍"),
			new MonasticTitleItem(1658, "征"),
			new MonasticTitleItem(1659, "非"),
			new MonasticTitleItem(1660, "石"),
			new MonasticTitleItem(1661, "厉"),
			new MonasticTitleItem(1662, "笫"),
			new MonasticTitleItem(1663, "实"),
			new MonasticTitleItem(1664, "谦"),
			new MonasticTitleItem(1665, "冥"),
			new MonasticTitleItem(1666, "眇"),
			new MonasticTitleItem(1667, "怀"),
			new MonasticTitleItem(1668, "恤"),
			new MonasticTitleItem(1669, "振"),
			new MonasticTitleItem(1670, "冲"),
			new MonasticTitleItem(1671, "持"),
			new MonasticTitleItem(1672, "满"),
			new MonasticTitleItem(1673, "究"),
			new MonasticTitleItem(1674, "敬"),
			new MonasticTitleItem(1675, "雨"),
			new MonasticTitleItem(1676, "溟"),
			new MonasticTitleItem(1677, "沐"),
			new MonasticTitleItem(1678, "润"),
			new MonasticTitleItem(1679, "枯"),
			new MonasticTitleItem(1680, "荣"),
			new MonasticTitleItem(1681, "孚"),
			new MonasticTitleItem(1682, "吒"),
			new MonasticTitleItem(1683, "邪"),
			new MonasticTitleItem(1684, "引"),
			new MonasticTitleItem(1685, "争"),
			new MonasticTitleItem(1686, "兕"),
			new MonasticTitleItem(1687, "矩"),
			new MonasticTitleItem(1688, "同"),
			new MonasticTitleItem(1689, "予"),
			new MonasticTitleItem(1690, "丑"),
			new MonasticTitleItem(1691, "杀"),
			new MonasticTitleItem(1692, "仓"),
			new MonasticTitleItem(1693, "宿"),
			new MonasticTitleItem(1694, "悦"),
			new MonasticTitleItem(1695, "茂"),
			new MonasticTitleItem(1696, "知"),
			new MonasticTitleItem(1697, "鸣"),
			new MonasticTitleItem(1698, "泽"),
			new MonasticTitleItem(1699, "裳"),
			new MonasticTitleItem(1700, "廷"),
			new MonasticTitleItem(1701, "庆"),
			new MonasticTitleItem(1702, "台"),
			new MonasticTitleItem(1703, "辅"),
			new MonasticTitleItem(1704, "拂"),
			new MonasticTitleItem(1705, "危"),
			new MonasticTitleItem(1706, "斧"),
			new MonasticTitleItem(1707, "栖"),
			new MonasticTitleItem(1708, "隙"),
			new MonasticTitleItem(1709, "谏"),
			new MonasticTitleItem(1710, "挈"),
			new MonasticTitleItem(1711, "禄"),
			new MonasticTitleItem(1712, "回"),
			new MonasticTitleItem(1713, "言"),
			new MonasticTitleItem(1714, "饴"),
			new MonasticTitleItem(1715, "怡"),
			new MonasticTitleItem(1716, "锡"),
			new MonasticTitleItem(1717, "解"),
			new MonasticTitleItem(1718, "容"),
			new MonasticTitleItem(1719, "云"),
			new MonasticTitleItem(1720, "爻"),
			new MonasticTitleItem(1721, "若"),
			new MonasticTitleItem(1722, "荧"),
			new MonasticTitleItem(1723, "攸"),
			new MonasticTitleItem(1724, "卉"),
			new MonasticTitleItem(1725, "炎"),
			new MonasticTitleItem(1726, "陵"),
			new MonasticTitleItem(1727, "临"),
			new MonasticTitleItem(1728, "誉"),
			new MonasticTitleItem(1729, "独"),
			new MonasticTitleItem(1730, "逝"),
			new MonasticTitleItem(1731, "涂"),
			new MonasticTitleItem(1732, "复"),
			new MonasticTitleItem(1733, "仪"),
			new MonasticTitleItem(1734, "远"),
			new MonasticTitleItem(1735, "蹊"),
			new MonasticTitleItem(1736, "忧"),
			new MonasticTitleItem(1737, "遵"),
			new MonasticTitleItem(1738, "翼"),
			new MonasticTitleItem(1739, "曲"),
			new MonasticTitleItem(1740, "训"),
			new MonasticTitleItem(1741, "意"),
			new MonasticTitleItem(1742, "济"),
			new MonasticTitleItem(1743, "衡"),
			new MonasticTitleItem(1744, "悔"),
			new MonasticTitleItem(1745, "辟"),
			new MonasticTitleItem(1746, "致"),
			new MonasticTitleItem(1747, "晖"),
			new MonasticTitleItem(1748, "震"),
			new MonasticTitleItem(1749, "安"),
			new MonasticTitleItem(1750, "铭"),
			new MonasticTitleItem(1751, "履"),
			new MonasticTitleItem(1752, "青"),
			new MonasticTitleItem(1753, "颛"),
			new MonasticTitleItem(1754, "晦"),
			new MonasticTitleItem(1755, "惟"),
			new MonasticTitleItem(1756, "幕"),
			new MonasticTitleItem(1757, "修"),
			new MonasticTitleItem(1758, "鉴"),
			new MonasticTitleItem(1759, "衰"),
			new MonasticTitleItem(1760, "犀"),
			new MonasticTitleItem(1761, "增"),
			new MonasticTitleItem(1762, "息"),
			new MonasticTitleItem(1763, "益"),
			new MonasticTitleItem(1764, "识"),
			new MonasticTitleItem(1765, "烛"),
			new MonasticTitleItem(1766, "伤"),
			new MonasticTitleItem(1767, "损"),
			new MonasticTitleItem(1768, "岑"),
			new MonasticTitleItem(1769, "达"),
			new MonasticTitleItem(1770, "处"),
			new MonasticTitleItem(1771, "忘"),
			new MonasticTitleItem(1772, "殃"),
			new MonasticTitleItem(1773, "砭"),
			new MonasticTitleItem(1774, "废"),
			new MonasticTitleItem(1775, "惑"),
			new MonasticTitleItem(1776, "惭"),
			new MonasticTitleItem(1777, "莺"),
			new MonasticTitleItem(1778, "焕"),
			new MonasticTitleItem(1779, "节"),
			new MonasticTitleItem(1780, "承"),
			new MonasticTitleItem(1781, "术"),
			new MonasticTitleItem(1782, "罗"),
			new MonasticTitleItem(1783, "空"),
			new MonasticTitleItem(1784, "介"),
			new MonasticTitleItem(1785, "随"),
			new MonasticTitleItem(1786, "应"),
			new MonasticTitleItem(1787, "旭"),
			new MonasticTitleItem(1788, "证"),
			new MonasticTitleItem(1789, "越"),
			new MonasticTitleItem(1790, "丕"),
			new MonasticTitleItem(1791, "逐"),
			new MonasticTitleItem(1792, "讼"),
			new MonasticTitleItem(1793, "徽"),
			new MonasticTitleItem(1794, "悬"),
			new MonasticTitleItem(1795, "融"),
			new MonasticTitleItem(1796, "址"),
			new MonasticTitleItem(1797, "听"),
			new MonasticTitleItem(1798, "毁"),
			new MonasticTitleItem(1799, "逆"),
			new MonasticTitleItem(1800, "煦"),
			new MonasticTitleItem(1801, "风"),
			new MonasticTitleItem(1802, "雷"),
			new MonasticTitleItem(1803, "兴"),
			new MonasticTitleItem(1804, "诟"),
			new MonasticTitleItem(1805, "仆"),
			new MonasticTitleItem(1806, "狱"),
			new MonasticTitleItem(1807, "梏"),
			new MonasticTitleItem(1808, "宵"),
			new MonasticTitleItem(1809, "妙"),
			new MonasticTitleItem(1810, "法"),
			new MonasticTitleItem(1811, "漆"),
			new MonasticTitleItem(1812, "消"),
			new MonasticTitleItem(1813, "奕"),
			new MonasticTitleItem(1814, "缟"),
			new MonasticTitleItem(1815, "谊"),
			new MonasticTitleItem(1816, "平"),
			new MonasticTitleItem(1817, "易"),
			new MonasticTitleItem(1818, "罔"),
			new MonasticTitleItem(1819, "胜"),
			new MonasticTitleItem(1820, "威"),
			new MonasticTitleItem(1821, "乐"),
			new MonasticTitleItem(1822, "奥"),
			new MonasticTitleItem(1823, "舒"),
			new MonasticTitleItem(1824, "喜"),
			new MonasticTitleItem(1825, "及"),
			new MonasticTitleItem(1826, "支"),
			new MonasticTitleItem(1827, "雅"),
			new MonasticTitleItem(1828, "绝"),
			new MonasticTitleItem(1829, "逸"),
			new MonasticTitleItem(1830, "佚"),
			new MonasticTitleItem(1831, "弦"),
			new MonasticTitleItem(1832, "嘻"),
			new MonasticTitleItem(1833, "鬼"),
			new MonasticTitleItem(1834, "愆"),
			new MonasticTitleItem(1835, "虞"),
			new MonasticTitleItem(1836, "机"),
			new MonasticTitleItem(1837, "隐"),
			new MonasticTitleItem(1838, "素"),
			new MonasticTitleItem(1839, "邻"),
			new MonasticTitleItem(1840, "盈"),
			new MonasticTitleItem(1841, "勉"),
			new MonasticTitleItem(1842, "亦"),
			new MonasticTitleItem(1843, "旡"),
			new MonasticTitleItem(1844, "羽"),
			new MonasticTitleItem(1845, "华"),
			new MonasticTitleItem(1846, "免"),
			new MonasticTitleItem(1847, "昭"),
			new MonasticTitleItem(1848, "哲"),
			new MonasticTitleItem(1849, "符"),
			new MonasticTitleItem(1850, "诲"),
			new MonasticTitleItem(1851, "变"),
			new MonasticTitleItem(1852, "轸"),
			new MonasticTitleItem(1853, "望"),
			new MonasticTitleItem(1854, "问"),
			new MonasticTitleItem(1855, "御"),
			new MonasticTitleItem(1856, "久"),
			new MonasticTitleItem(1857, "断"),
			new MonasticTitleItem(1858, "阔"),
			new MonasticTitleItem(1859, "钺"),
			new MonasticTitleItem(1860, "庚"),
			new MonasticTitleItem(1861, "硕"),
			new MonasticTitleItem(1862, "铄"),
			new MonasticTitleItem(1863, "仁"),
			new MonasticTitleItem(1864, "余"),
			new MonasticTitleItem(1865, "冰"),
			new MonasticTitleItem(1866, "鸿"),
			new MonasticTitleItem(1867, "旅"),
			new MonasticTitleItem(1868, "仲"),
			new MonasticTitleItem(1869, "泣"),
			new MonasticTitleItem(1870, "尚"),
			new MonasticTitleItem(1871, "尸"),
			new MonasticTitleItem(1872, "摧"),
			new MonasticTitleItem(1873, "瑕"),
			new MonasticTitleItem(1874, "豹"),
			new MonasticTitleItem(1875, "螭"),
			new MonasticTitleItem(1876, "恃"),
			new MonasticTitleItem(1877, "旌"),
			new MonasticTitleItem(1878, "兰"),
			new MonasticTitleItem(1879, "觉"),
			new MonasticTitleItem(1880, "依"),
			new MonasticTitleItem(1881, "笃"),
			new MonasticTitleItem(1882, "取"),
			new MonasticTitleItem(1883, "秉"),
			new MonasticTitleItem(1884, "亢"),
			new MonasticTitleItem(1885, "衍"),
			new MonasticTitleItem(1886, "悯"),
			new MonasticTitleItem(1887, "聪"),
			new MonasticTitleItem(1888, "庶"),
			new MonasticTitleItem(1889, "清"),
			new MonasticTitleItem(1890, "恭"),
			new MonasticTitleItem(1891, "慕"),
			new MonasticTitleItem(1892, "佐"),
			new MonasticTitleItem(1893, "永"),
			new MonasticTitleItem(1894, "营"),
			new MonasticTitleItem(1895, "赐"),
			new MonasticTitleItem(1896, "挹"),
			new MonasticTitleItem(1897, "赫"),
			new MonasticTitleItem(1898, "洗"),
			new MonasticTitleItem(1899, "甫"),
			new MonasticTitleItem(1900, "纪"),
			new MonasticTitleItem(1901, "玑"),
			new MonasticTitleItem(1902, "溯"),
			new MonasticTitleItem(1903, "妖"),
			new MonasticTitleItem(1904, "珠"),
			new MonasticTitleItem(1905, "梦"),
			new MonasticTitleItem(1906, "谕"),
			new MonasticTitleItem(1907, "禁"),
			new MonasticTitleItem(1908, "鼎"),
			new MonasticTitleItem(1909, "觞"),
			new MonasticTitleItem(1910, "怠"),
			new MonasticTitleItem(1911, "恢"),
			new MonasticTitleItem(1912, "文"),
			new MonasticTitleItem(1913, "质"),
			new MonasticTitleItem(1914, "弥"),
			new MonasticTitleItem(1915, "肃"),
			new MonasticTitleItem(1916, "鱼"),
			new MonasticTitleItem(1917, "创"),
			new MonasticTitleItem(1918, "迹"),
			new MonasticTitleItem(1919, "林"),
			new MonasticTitleItem(1920, "珑"),
			new MonasticTitleItem(1921, "玲"),
			new MonasticTitleItem(1922, "鹿"),
			new MonasticTitleItem(1923, "弋"),
			new MonasticTitleItem(1924, "收"),
			new MonasticTitleItem(1925, "世"),
			new MonasticTitleItem(1926, "宁"),
			new MonasticTitleItem(1927, "莳"),
			new MonasticTitleItem(1928, "伦"),
			new MonasticTitleItem(1929, "尘"),
			new MonasticTitleItem(1930, "冢"),
			new MonasticTitleItem(1931, "魂"),
			new MonasticTitleItem(1932, "魄"),
			new MonasticTitleItem(1933, "狐"),
			new MonasticTitleItem(1934, "拟"),
			new MonasticTitleItem(1935, "鸾"),
			new MonasticTitleItem(1936, "药"),
			new MonasticTitleItem(1937, "露"),
			new MonasticTitleItem(1938, "照"),
			new MonasticTitleItem(1939, "愁"),
			new MonasticTitleItem(1940, "昧"),
			new MonasticTitleItem(1941, "星"),
			new MonasticTitleItem(1942, "叹"),
			new MonasticTitleItem(1943, "宇"),
			new MonasticTitleItem(1944, "破"),
			new MonasticTitleItem(1945, "智"),
			new MonasticTitleItem(1946, "合"),
			new MonasticTitleItem(1947, "沌"),
			new MonasticTitleItem(1948, "炉"),
			new MonasticTitleItem(1949, "罡"),
			new MonasticTitleItem(1950, "霞"),
			new MonasticTitleItem(1951, "遗")
		};
	}
}
