using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class SecretInformationSpecialCondition : ConfigData<SecretInformationSpecialConditionItem, short>
{
	public static class DefKey
	{
		public const short None = 0;

		public const short SectBecomeEnemy = 3;

		public const short TaiwuFight = 17;

		public const short CompareCombatPoint = 23;

		public const short BreakTheLaw = 54;
	}

	public static class DefValue
	{
		public static SecretInformationSpecialConditionItem None => Instance[(short)0];

		public static SecretInformationSpecialConditionItem SectBecomeEnemy => Instance[(short)3];

		public static SecretInformationSpecialConditionItem TaiwuFight => Instance[(short)17];

		public static SecretInformationSpecialConditionItem CompareCombatPoint => Instance[(short)23];

		public static SecretInformationSpecialConditionItem BreakTheLaw => Instance[(short)54];
	}

	public static SecretInformationSpecialCondition Instance = new SecretInformationSpecialCondition();

	private readonly HashSet<string> RequiredFields = new HashSet<string> { "CalcSectRule", "CalcOrganization", "TemplateId", "Name" };

	internal override int ToInt(short value)
	{
		return value;
	}

	internal override short ToTemplateId(int value)
	{
		return (short)value;
	}

	private void CreateItems0()
	{
		_dataArray.Add(new SecretInformationSpecialConditionItem(0, 0, new short[5], ESecretInformationSpecialConditionCalculate.None, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(1, 1, new short[5] { 20, 10, 40, 30, 50 }, ESecretInformationSpecialConditionCalculate.SameSect, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(2, 2, new short[5], ESecretInformationSpecialConditionCalculate.SectJustice, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(3, 3, new short[5] { 0, 10, 20, -10, 30 }, ESecretInformationSpecialConditionCalculate.SectBecomeEnemy, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(4, 4, new short[5] { 30, 20, 40, 50, 60 }, ESecretInformationSpecialConditionCalculate.ForbidMarriage, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(5, 5, new short[5], ESecretInformationSpecialConditionCalculate.IsPublished, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(6, 6, new short[5] { 20, 10, 30, 0, 40 }, ESecretInformationSpecialConditionCalculate.IsRevealed, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(7, 7, new short[5] { 20, 0, 10, 0, 30 }, ESecretInformationSpecialConditionCalculate.IsRevealedSingle, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(8, 8, new short[5] { 20, 0, 10, 0, 30 }, ESecretInformationSpecialConditionCalculate.HasCouple, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(9, 9, new short[5], ESecretInformationSpecialConditionCalculate.NotFame, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(10, 10, new short[5], ESecretInformationSpecialConditionCalculate.IsMonk, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(11, 11, new short[5], ESecretInformationSpecialConditionCalculate.ForbidWine, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(12, 12, new short[5], ESecretInformationSpecialConditionCalculate.ForbidPoison, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(13, 13, new short[5], ESecretInformationSpecialConditionCalculate.ForbidItem, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(14, 14, new short[5], ESecretInformationSpecialConditionCalculate.HasLove, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(15, 15, new short[5], ESecretInformationSpecialConditionCalculate.HasRelation, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(16, 16, new short[5], ESecretInformationSpecialConditionCalculate.IsKidnapped, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(17, 17, new short[5], ESecretInformationSpecialConditionCalculate.TaiwuFight, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(18, 18, new short[5], ESecretInformationSpecialConditionCalculate.TaiwuSteal, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(19, 19, new short[5], ESecretInformationSpecialConditionCalculate.TaiwuScam, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(20, 20, new short[5], ESecretInformationSpecialConditionCalculate.TaiwuRob, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(21, 21, new short[5], ESecretInformationSpecialConditionCalculate.TaiwuRescueEscape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(22, 22, new short[5], ESecretInformationSpecialConditionCalculate.CharRescueEscape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(23, 23, new short[5], ESecretInformationSpecialConditionCalculate.CompareCombatPoint, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(24, 24, new short[5], ESecretInformationSpecialConditionCalculate.CharFight, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(25, 25, new short[5], ESecretInformationSpecialConditionCalculate.RefuseKeep, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(26, 26, new short[5], ESecretInformationSpecialConditionCalculate.CharRescue, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(27, 27, new short[5], ESecretInformationSpecialConditionCalculate.CharWin, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(28, 28, new short[5], ESecretInformationSpecialConditionCalculate.CharJudge, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(29, 29, new short[5], ESecretInformationSpecialConditionCalculate.CharKidnap, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(30, 30, new short[5], ESecretInformationSpecialConditionCalculate.TaiwuEscape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(31, 31, new short[5], ESecretInformationSpecialConditionCalculate.CharEscape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(32, 32, new short[5], ESecretInformationSpecialConditionCalculate.StartFight, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(33, 33, new short[5], ESecretInformationSpecialConditionCalculate.StartLifeSkillCombat, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(34, 34, new short[5], ESecretInformationSpecialConditionCalculate.ChooseRope, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(35, 35, new short[5], ESecretInformationSpecialConditionCalculate.KidnapWithRope, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(36, 36, new short[5], ESecretInformationSpecialConditionCalculate.CharAdore, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(37, 37, new short[5], ESecretInformationSpecialConditionCalculate.TaiwuAdore, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(38, 38, new short[5], ESecretInformationSpecialConditionCalculate.TaiwuDeleteInfomation, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(39, 39, new short[5], ESecretInformationSpecialConditionCalculate.CharDeleteInfomation, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(40, 40, new short[5], ESecretInformationSpecialConditionCalculate.CharBreakUp, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(41, 41, new short[5], ESecretInformationSpecialConditionCalculate.TaiwuEndAdored, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(42, 42, new short[5], ESecretInformationSpecialConditionCalculate.CharEndAdored, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(43, 43, new short[5], ESecretInformationSpecialConditionCalculate.Forgive, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(44, 44, new short[5], ESecretInformationSpecialConditionCalculate.NotForgiveRape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(45, 45, new short[5], ESecretInformationSpecialConditionCalculate.ApplyOfLeader, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(46, 46, new short[5], ESecretInformationSpecialConditionCalculate.LawBreaker, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(47, 47, new short[5], ESecretInformationSpecialConditionCalculate.AskCharKeep, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(48, 48, new short[5], ESecretInformationSpecialConditionCalculate.AskCharRelease, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(49, 49, new short[5], ESecretInformationSpecialConditionCalculate.AskCharBreakup, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(50, 52, new short[5], ESecretInformationSpecialConditionCalculate.ShowFristContent, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(51, 50, new short[5], ESecretInformationSpecialConditionCalculate.BreakupWithChar, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(52, 51, new short[5], ESecretInformationSpecialConditionCalculate.ForceBreakupWithChar, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(53, 53, new short[5], ESecretInformationSpecialConditionCalculate.ActorAlive, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(54, 54, new short[5], ESecretInformationSpecialConditionCalculate.BreakTheLaw, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(55, 55, new short[5], ESecretInformationSpecialConditionCalculate.CasualtyInSect, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(56, 56, new short[5], ESecretInformationSpecialConditionCalculate.KillFameLine, ESecretInformationSpecialConditionCalcFameLine.Renowned, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(57, 57, new short[5], ESecretInformationSpecialConditionCalculate.KillFameLine, ESecretInformationSpecialConditionCalcFameLine.Badboy, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(58, 58, new short[5], ESecretInformationSpecialConditionCalculate.KillFameLine, ESecretInformationSpecialConditionCalcFameLine.SuperStar, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(59, 59, new short[5], ESecretInformationSpecialConditionCalculate.KidnapFameLine, ESecretInformationSpecialConditionCalcFameLine.Renowned, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
	}

	private void CreateItems1()
	{
		_dataArray.Add(new SecretInformationSpecialConditionItem(60, 60, new short[5], ESecretInformationSpecialConditionCalculate.KidnapFameLine, ESecretInformationSpecialConditionCalcFameLine.Badboy, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(61, 61, new short[5], ESecretInformationSpecialConditionCalculate.KidnapFameLine, ESecretInformationSpecialConditionCalcFameLine.SuperStar, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(62, 62, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(63, 63, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(64, 64, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(65, 65, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(66, 66, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(67, 67, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(68, 68, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(69, 69, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(70, 70, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(71, 71, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(72, 72, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(73, 73, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(74, 74, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(75, 75, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(76, 76, new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(77, 77, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.GainChild, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 45, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(78, 78, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.GainChild, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 46, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(79, 79, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.GainChild, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 47, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(80, 80, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeLover, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 48, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(81, 81, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeLover, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 49, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(82, 82, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeLover, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 50, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(83, 83, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeHusband, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 51, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(84, 84, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeHusband, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 52, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(85, 85, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeHusband, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 53, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(86, 86, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexInvalid, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 54, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(87, 87, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexInvalid, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 55, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(88, 88, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexInvalid, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 56, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(89, 89, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexNotAllow, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 57, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(90, 90, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexNotAllow, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 58, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(91, 91, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexNotAllow, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 59, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(92, 92, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Date, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 60, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(93, 93, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Date, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 61, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(94, 94, new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Date, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 62, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(95, 95, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(96, 96, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(97, 97, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(98, 98, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(99, 99, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(100, 100, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(101, 101, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(102, 102, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(103, 103, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(104, 104, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(105, 105, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(106, 106, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(107, 107, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(108, 108, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(109, 109, new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(110, 110, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(111, 111, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(112, 112, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(113, 113, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(114, 114, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(115, 115, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(116, 116, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(117, 117, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(118, 118, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(119, 119, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
	}

	private void CreateItems2()
	{
		_dataArray.Add(new SecretInformationSpecialConditionItem(120, 120, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(121, 121, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(122, 122, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(123, 123, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(124, 124, new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(125, 125, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(126, 126, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(127, 127, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(128, 128, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(129, 129, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(130, 130, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(131, 131, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(132, 132, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(133, 133, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(134, 134, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(135, 135, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(136, 136, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(137, 137, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(138, 138, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(139, 139, new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(140, 140, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(141, 141, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(142, 142, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(143, 143, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(144, 144, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(145, 145, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(146, 146, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(147, 147, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(148, 148, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(149, 149, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(150, 150, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(151, 151, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(152, 152, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(153, 153, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(154, 154, new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(155, 155, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(156, 156, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(157, 157, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(158, 158, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(159, 159, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(160, 160, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(161, 161, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(162, 162, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(163, 163, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(164, 164, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(165, 165, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(166, 166, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(167, 167, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(168, 168, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(169, 169, new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(170, 170, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(171, 171, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(172, 172, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(173, 173, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(174, 174, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(175, 175, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(176, 176, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(177, 177, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(178, 178, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(179, 179, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
	}

	private void CreateItems3()
	{
		_dataArray.Add(new SecretInformationSpecialConditionItem(180, 180, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(181, 181, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(182, 182, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(183, 183, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(184, 184, new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(185, 185, new short[5], ESecretInformationSpecialConditionCalculate.BanEating, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, 19, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(186, 186, new short[5], ESecretInformationSpecialConditionCalculate.BanEating, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, 44, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(187, 187, new short[5], ESecretInformationSpecialConditionCalculate.BanEating, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, 164, -1));
	}

	public override void Init()
	{
		base.Init();
		_dataArray = new List<SecretInformationSpecialConditionItem>(188);
		CreateItems0();
		CreateItems1();
		CreateItems2();
		CreateItems3();
	}
}
