using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class SkillBreakBonusEffectImplement : ConfigData<SkillBreakBonusEffectImplementItem, sbyte>
{
	public static SkillBreakBonusEffectImplement Instance = new SkillBreakBonusEffectImplement();

	private readonly HashSet<string> RequiredFields = new HashSet<string> { "AddRequirementType", "ReduceCostBreathType", "ReduceCostStanceType", "ReduceCastFrameType", "AddMaxPowerType", "TemplateId" };

	internal override int ToInt(sbyte value)
	{
		return value;
	}

	internal override sbyte ToTemplateId(int value)
	{
		return (sbyte)value;
	}

	private void CreateItems0()
	{
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(0, 0, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(1, 1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(2, 2, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(3, 3, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(4, -1, 8, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(5, -1, 9, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(6, -1, -1, 6, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(7, -1, -1, 7, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(8, -1, -1, 10, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(9, -1, -1, 11, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(10, -1, -1, -1, 4, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(11, -1, -1, -1, 5, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(12, -1, -1, -1, 14, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(13, -1, -1, -1, 15, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(14, -1, -1, -1, -1, 13, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(15, -1, -1, -1, -1, 12, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(16, -1, -1, -1, -1, -1, addInjuryStep: true, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(17, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 100, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(18, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: true, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(19, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: true, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(20, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 300, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(21, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 300, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(22, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 200, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(23, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 200, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(24, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 100, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(25, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 100, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(26, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 100, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(27, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 100, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(28, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4] { 1, 0, 0, 0 }, 1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(29, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4] { 0, 0, 1, 0 }, 3, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(30, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4] { 0, 0, 0, 1 }, 4, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(31, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4] { 0, 1, 0, 0 }, 2, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(32, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: true, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(33, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: true, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(34, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: true, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(35, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: true, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(36, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: true, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(37, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: true, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(38, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: true, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(39, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 2, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(40, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: true, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(41, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: true, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(42, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: true, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(43, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: true));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(44, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: true, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(45, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: true, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(46, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: true, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(47, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: true, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(48, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: true, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(49, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: true, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(50, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 10, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(51, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 100, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(52, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: true, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(53, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: true, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(54, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 100, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(55, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: true, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(56, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: false, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: true, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
		_dataArray.Add(new SkillBreakBonusEffectImplementItem(57, -1, -1, -1, -1, -1, addInjuryStep: false, addFatalStep: false, addMindStep: false, 0, 0, 0, 0, 0, 0, addMainAttribute: false, addHitAvoidStrength: false, addHitAvoidTechnique: false, addHitAvoidSpeed: false, addHitAvoidMind: false, relationAddHitMind: false, relationAddAvoidMind: false, reduceRequirements: false, addPower: true, innerRatioChangeRange: false, new sbyte[4], -1, 0, attackRangeForward: false, attackRangeBackward: false, makeDamage: false, attackSkillHitFactor: false, poisonFactor: false, costMobilityByFrame: false, costMobilityByMove: false, 0, agileSkillHitFactor: false, fightBackPower: false, bouncePower: false, defensePenetrateResistFactor: false, defenseAvoidFactor: false));
	}

	public override void Init()
	{
		base.Init();
		_dataArray = new List<SkillBreakBonusEffectImplementItem>(58);
		CreateItems0();
	}
}
