using System;
using System.Collections.Generic;
using Config.Common;
using Config.ConfigCells;
using GameData.Utilities;

namespace Config;

[Serializable]
public class TaskCondition : ConfigData<TaskConditionItem, int>
{
	public static TaskCondition Instance = new TaskCondition();

	private readonly HashSet<string> RequiredFields = new HashSet<string>
	{
		"Adventure", "Items", "CharacterTemplateId", "StateTemplateId", "MapBlockList", "Building", "ProfessionSkill", "OrTaskCondition", "AndTaskCondition", "TemplateId",
		"Type", "GlobalArgBoxKey"
	};

	internal override int ToInt(int value)
	{
		return value;
	}

	internal override int ToTemplateId(int value)
	{
		return value;
	}

	private void CreateItems0()
	{
		_dataArray.Add(new TaskConditionItem(0, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 97, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.CurrentArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(1, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 6, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.CurrentArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(2, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 6, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.CurrentArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(3, ETaskConditionType.CharacterHasItems, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 210, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(4, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 0, 3 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(5, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 98, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.CurrentArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(6, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 102, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.CurrentArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(7, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 100, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.CurrentArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(8, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 100, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.CurrentArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(9, ETaskConditionType.CharacterHasItems, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 229, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(10, ETaskConditionType.CharacterHasItems, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 229, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(11, ETaskConditionType.GlobalArgBoxKeyExists, isReverseCondition: false, 0, "TryStealBoat", new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(12, ETaskConditionType.SettlementHasBuilding, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short> { 16 }, 203, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(13, ETaskConditionType.GlobalArgBoxValueRange, isReverseCondition: false, 0, "ChatWithANiu", new IntPair(0, 1), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(14, ETaskConditionType.GlobalArgBoxValueRange, isReverseCondition: false, 0, "ChatWithXiaomao", new IntPair(0, 1), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(15, ETaskConditionType.GlobalArgBoxValueRange, isReverseCondition: false, 0, "ChatWithHuanyue", new IntPair(0, 1), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(16, ETaskConditionType.GlobalArgBoxValueRange, isReverseCondition: false, 0, "DeliverVegetable", new IntPair(2, 4), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(17, ETaskConditionType.CharacterExists, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 465, ETaskConditionCharacterType.ConvertedFixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(18, ETaskConditionType.CharacterExists, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 466, ETaskConditionCharacterType.ConvertedFixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(19, ETaskConditionType.CharacterExists, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 463, ETaskConditionCharacterType.ConvertedFixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(20, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int> { 17, 18, 19 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(21, ETaskConditionType.CharacterAtAdventure, isReverseCondition: false, 0, null, new IntPair(0, 0), 102, new List<PresetItemWithCount>(), 463, ETaskConditionCharacterType.ConvertedFixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(22, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(23, ETaskConditionType.CharacterHasItems, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 197, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(24, ETaskConditionType.CharacterHasItems, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 197, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(25, ETaskConditionType.SettlementHasBuilding, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, 45, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(26, ETaskConditionType.SettlementHasBuilding, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, 45, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(27, ETaskConditionType.FunctionUnlocked, isReverseCondition: false, 5, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(28, ETaskConditionType.FunctionUnlocked, isReverseCondition: false, 15, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(29, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(30, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 104, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(31, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 479, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(32, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 480, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(33, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 481, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(34, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 482, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(35, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 483, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(36, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 484, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(37, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 485, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(38, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 486, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(39, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 487, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(40, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 31, 32, 33, 34, 35, 36, 37, 38, 39 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(41, ETaskConditionType.ConditionOr, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 31, 32, 33, 34, 35, 36, 37, 38, 39 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(42, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 479, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(43, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 480, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(44, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 481, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(45, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 482, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(46, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 483, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(47, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 484, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(48, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 485, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(49, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 486, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(50, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 487, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(51, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 42, 43, 44, 45, 46, 47, 48, 49, 50 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(52, ETaskConditionType.ConditionOr, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 42, 43, 44, 45, 46, 47, 48, 49, 50 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(53, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 129, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(54, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 138, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(55, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 147, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(56, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 156, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(57, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 165, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(58, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 174, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(59, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 183, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
	}

	private void CreateItems1()
	{
		_dataArray.Add(new TaskConditionItem(60, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 192, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(61, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 201, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(62, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 53, 54, 55, 56, 57, 58, 59, 60, 61 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(63, ETaskConditionType.ConditionOr, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 53, 54, 55, 56, 57, 58, 59, 60, 61 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(64, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 101, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(65, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 105, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(66, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 114, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(67, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 111, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(68, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 108, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(69, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 110, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(70, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 109, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(71, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 113, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(72, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 116, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(73, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 115, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(74, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 112, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(75, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 66, 67, 68, 69, 70, 71, 72, 73, 74 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(76, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 105, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(77, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 114, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(78, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 111, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(79, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 108, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(80, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 110, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(81, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 109, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(82, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 113, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(83, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 116, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(84, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 115, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(85, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 112, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(86, ETaskConditionType.ConditionAnd, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int> { 77, 78, 79, 80, 81, 82, 83, 84, 85 }));
		_dataArray.Add(new TaskConditionItem(87, ETaskConditionType.SwordTombStatus, isReverseCondition: false, 2, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 129, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(88, ETaskConditionType.SwordTombStatus, isReverseCondition: false, 2, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 138, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(89, ETaskConditionType.SwordTombStatus, isReverseCondition: false, 2, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 147, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(90, ETaskConditionType.SwordTombStatus, isReverseCondition: false, 2, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 156, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(91, ETaskConditionType.SwordTombStatus, isReverseCondition: false, 2, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 165, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(92, ETaskConditionType.SwordTombStatus, isReverseCondition: false, 2, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 174, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(93, ETaskConditionType.SwordTombStatus, isReverseCondition: false, 2, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 183, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(94, ETaskConditionType.SwordTombStatus, isReverseCondition: false, 2, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 192, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(95, ETaskConditionType.SwordTombStatus, isReverseCondition: false, 2, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 201, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(96, ETaskConditionType.ConditionAnd, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int> { 87, 88, 89, 90, 91, 92, 93, 94, 95 }));
		_dataArray.Add(new TaskConditionItem(97, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 452, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short> { 128 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(98, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 452, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short> { 129 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(99, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 452, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short> { 130 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(100, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 452, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short> { 131 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(101, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 452, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short> { 132 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(102, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 452, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short> { 133 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(103, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 452, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short> { 134 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(104, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 452, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short> { 135 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(105, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 452, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short> { 136 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(106, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 97, 98, 99, 100, 101, 102, 103, 104, 105 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(107, ETaskConditionType.ConditionOr, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 97, 98, 99, 100, 101, 102, 103, 104, 105 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(108, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.BrokenArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(109, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.BrokenArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(110, ETaskConditionType.FunctionUnlocked, isReverseCondition: false, 21, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(111, ETaskConditionType.CharacterHasItems, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 199, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(112, ETaskConditionType.CharacterHasItems, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 199, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(113, ETaskConditionType.SettlementHasBuilding, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, 50, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(114, ETaskConditionType.SettlementHasBuilding, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, 50, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(115, ETaskConditionType.ConditionAnd, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int> { 111, 114 }));
		_dataArray.Add(new TaskConditionItem(116, ETaskConditionType.ConditionAnd, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int> { 112, 113 }));
		_dataArray.Add(new TaskConditionItem(117, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(118, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 115, 116 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(119, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 99, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
	}

	private void CreateItems2()
	{
		_dataArray.Add(new TaskConditionItem(120, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 99, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(121, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 39, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(122, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 40, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(123, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 41, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(124, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 42, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(125, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 43, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(126, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 44, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(127, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 45, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(128, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 46, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(129, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 47, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(130, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 121, 122, 123, 124, 125, 126, 127, 128, 129 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(131, ETaskConditionType.CharacterAtMapArea, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 39, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(132, ETaskConditionType.CharacterAtMapArea, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 40, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(133, ETaskConditionType.CharacterAtMapArea, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 41, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(134, ETaskConditionType.CharacterAtMapArea, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 42, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(135, ETaskConditionType.CharacterAtMapArea, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 43, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(136, ETaskConditionType.CharacterAtMapArea, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 44, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(137, ETaskConditionType.CharacterAtMapArea, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 45, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(138, ETaskConditionType.CharacterAtMapArea, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 46, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(139, ETaskConditionType.CharacterAtMapArea, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 47, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(140, ETaskConditionType.ConditionAnd, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int> { 131, 132, 133, 134, 135, 136, 137, 138, 139 }));
		_dataArray.Add(new TaskConditionItem(141, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 39, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(142, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 40, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(143, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 41, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(144, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 42, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(145, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 43, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(146, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 44, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(147, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 45, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(148, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 46, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(149, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1203, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 47, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(150, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 141, 142, 143, 144, 145, 146, 147, 148, 149 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(151, ETaskConditionType.ConditionAnd, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int> { 141, 142, 143, 144, 145, 146, 147, 148, 149 }));
		_dataArray.Add(new TaskConditionItem(152, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(1, 5), -1, new List<PresetItemWithCount>(), 39, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(153, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(1, 5), -1, new List<PresetItemWithCount>(), 40, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(154, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(1, 5), -1, new List<PresetItemWithCount>(), 41, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(155, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(1, 5), -1, new List<PresetItemWithCount>(), 42, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(156, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(1, 5), -1, new List<PresetItemWithCount>(), 43, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(157, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(1, 5), -1, new List<PresetItemWithCount>(), 44, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(158, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(1, 5), -1, new List<PresetItemWithCount>(), 45, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(159, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(1, 5), -1, new List<PresetItemWithCount>(), 46, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(160, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(1, 5), -1, new List<PresetItemWithCount>(), 47, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(161, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(5, 7), -1, new List<PresetItemWithCount>(), 39, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(162, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(5, 7), -1, new List<PresetItemWithCount>(), 40, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(163, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(5, 7), -1, new List<PresetItemWithCount>(), 41, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(164, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(5, 7), -1, new List<PresetItemWithCount>(), 42, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(165, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(5, 7), -1, new List<PresetItemWithCount>(), 43, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(166, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(5, 7), -1, new List<PresetItemWithCount>(), 44, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(167, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(5, 7), -1, new List<PresetItemWithCount>(), 45, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(168, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(5, 7), -1, new List<PresetItemWithCount>(), 46, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(169, ETaskConditionType.JuniorXiangshuTaskStatus, isReverseCondition: false, 0, null, new IntPair(5, 7), -1, new List<PresetItemWithCount>(), 47, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(170, ETaskConditionType.JuniorXiangshuTaskCompleteAmount, isReverseCondition: false, 0, null, new IntPair(8, 99), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(171, ETaskConditionType.CharacterHasItems, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 198, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(172, ETaskConditionType.CharacterHasItems, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 198, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(173, ETaskConditionType.SettlementHasBuilding, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, 51, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(174, ETaskConditionType.SettlementHasBuilding, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, 51, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(175, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 446, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(176, ETaskConditionType.CharacterHasItems, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 230, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(177, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 106, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(178, ETaskConditionType.CharacterHasItems, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>
		{
			new PresetItemWithCount("Misc", 228, 1)
		}, -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(179, ETaskConditionType.CharacterAtMapArea, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 447, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
	}

	private void CreateItems3()
	{
		_dataArray.Add(new TaskConditionItem(180, ETaskConditionType.GlobalArgBoxValueRange, isReverseCondition: false, 0, "DefeatXiangshuMinion", new IntPair(3, 99), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(181, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 107, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(182, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 183, 184, 185, 186, 187, 188, 189, 190, 191 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(183, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 141, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(184, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 138, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(185, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 135, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(186, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 137, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(187, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 136, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(188, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 140, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(189, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 143, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(190, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 142, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(191, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 139, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.TaiwuVillageArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(192, ETaskConditionType.MartialArtTournamentPreparing, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(193, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 129, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(194, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 138, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(195, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 147, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(196, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 156, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(197, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 165, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(198, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 174, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(199, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 183, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(200, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 192, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(201, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 201, ETaskConditionCharacterType.XiangshuAvatar, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(202, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 193, 194, 195, 196, 197, 198, 199, 200, 201 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(203, ETaskConditionType.ConditionOr, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 193, 194, 195, 196, 197, 198, 199, 200, 201 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(204, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 111, 113 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(205, ETaskConditionType.FavorabilityToTaiwu, isReverseCondition: false, 0, null, new IntPair(12001, 99999), -1, new List<PresetItemWithCount>(), 39, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(206, ETaskConditionType.FavorabilityToTaiwu, isReverseCondition: false, 0, null, new IntPair(12001, 99999), -1, new List<PresetItemWithCount>(), 40, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(207, ETaskConditionType.FavorabilityToTaiwu, isReverseCondition: false, 0, null, new IntPair(12001, 99999), -1, new List<PresetItemWithCount>(), 41, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(208, ETaskConditionType.FavorabilityToTaiwu, isReverseCondition: false, 0, null, new IntPair(12001, 99999), -1, new List<PresetItemWithCount>(), 42, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(209, ETaskConditionType.FavorabilityToTaiwu, isReverseCondition: false, 0, null, new IntPair(12001, 99999), -1, new List<PresetItemWithCount>(), 43, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(210, ETaskConditionType.FavorabilityToTaiwu, isReverseCondition: false, 0, null, new IntPair(12001, 99999), -1, new List<PresetItemWithCount>(), 44, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(211, ETaskConditionType.FavorabilityToTaiwu, isReverseCondition: false, 0, null, new IntPair(12001, 99999), -1, new List<PresetItemWithCount>(), 45, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(212, ETaskConditionType.FavorabilityToTaiwu, isReverseCondition: false, 0, null, new IntPair(12001, 99999), -1, new List<PresetItemWithCount>(), 46, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(213, ETaskConditionType.FavorabilityToTaiwu, isReverseCondition: false, 0, null, new IntPair(12001, 99999), -1, new List<PresetItemWithCount>(), 47, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(214, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 205, 206, 207, 208, 209, 210, 211, 212, 213 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(215, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: false, 1202, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(216, ETaskConditionType.CharacterHasItemSubType, isReverseCondition: true, 1202, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(217, ETaskConditionType.GlobalArgBoxKeyExists, isReverseCondition: false, 0, "WaitForRanchenVisit", new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(218, ETaskConditionType.GlobalArgBoxKeyExists, isReverseCondition: false, 0, "WaitForReincarnationOpen", new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(219, ETaskConditionType.GlobalArgBoxKeyExists, isReverseCondition: false, 0, "WaitForPurpleBambooAppear", new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(220, ETaskConditionType.CharacterAtAdventure, isReverseCondition: false, 0, null, new IntPair(0, 0), 102, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(221, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 171, 174 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(222, ETaskConditionType.IsInAdventure, isReverseCondition: false, 0, null, new IntPair(0, 0), 102, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(223, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 9, 222 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(224, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 222, 20 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(225, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 27, 222 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(226, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 12, 222 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(227, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 21, 222 }, new List<int>()));
		_dataArray.Add(new TaskConditionItem(228, ETaskConditionType.AdventureVisible, isReverseCondition: false, 0, null, new IntPair(0, 0), 103, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(229, ETaskConditionType.GlobalArgBoxKeyExists, isReverseCondition: false, 0, "DaoshiAskForWildFood", new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(230, ETaskConditionType.ProfessionSkillValid, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, 40, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(231, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(232, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 2, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(233, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 3, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(234, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 4, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(235, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 5, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(236, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 6, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(237, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 7, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(238, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 8, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(239, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 9, new List<short>(), -1, -1, new List<int>(), new List<int>()));
	}

	private void CreateItems4()
	{
		_dataArray.Add(new TaskConditionItem(240, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 10, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(241, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 11, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(242, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 12, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(243, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 13, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(244, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 14, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(245, ETaskConditionType.StateTemplateVisited, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, 15, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(246, ETaskConditionType.ConditionAnd, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>
		{
			231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
			241, 242, 243, 244, 245
		}));
		_dataArray.Add(new TaskConditionItem(247, ETaskConditionType.CharacterExists, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), 446, ETaskConditionCharacterType.FixedCharacter, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(248, ETaskConditionType.CharacterAtMapBlock, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Taiwu, ETaskConditionAreaType.Invalid, -1, new List<short> { 0 }, -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(249, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 176, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.AnyArea, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(250, ETaskConditionType.AdventureVisible, isReverseCondition: true, 0, null, new IntPair(0, 0), 106, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(251, ETaskConditionType.ConditionAnd, isReverseCondition: true, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int> { 66, 67, 68, 69, 70, 71, 72, 73, 74 }));
		_dataArray.Add(new TaskConditionItem(252, ETaskConditionType.GlobalArgBoxKeyExists, isReverseCondition: false, 0, "ConchShip_PresetKey_FuyuHiltGuiding", new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int>(), new List<int>()));
		_dataArray.Add(new TaskConditionItem(253, ETaskConditionType.ConditionOr, isReverseCondition: false, 0, null, new IntPair(0, 0), -1, new List<PresetItemWithCount>(), -1, ETaskConditionCharacterType.Invalid, ETaskConditionAreaType.Invalid, -1, new List<short>(), -1, -1, new List<int> { 252, 29 }, new List<int>()));
	}

	public override void Init()
	{
		base.Init();
		_dataArray = new List<TaskConditionItem>(254);
		CreateItems0();
		CreateItems1();
		CreateItems2();
		CreateItems3();
		CreateItems4();
	}
}
